### ISSUE TITLE
[ENHANCEMENTS] how to upgrade 

### ISSUE THREAD

**Issue by barto95100** [tobychui/zoraxy#104]
Just a question how to update to V3 when is installed and build from source ?

loose the configuration and certificate ? renew, other ?

**Comment by tobychui** [comment]
There is no upgrade to the v3 from v2. I would recommend cloning the v3 to a different folder and build from there.
To move the certificates from Zoraxy v2 to v3, rename the file extension from `.crt` to `.pem` in the 'conf/certs/' folder. Other than that the rest of the rules have to be manually updated. You can find the new config structure over [here](https://github.com/tobychui/zoraxy/wiki/Add-Routing-Via-Config-File).

**Comment by barto95100** [comment]
It's OK

for other people this is the structure diff V2 to V3:

V2
```
{
 "ProxyType": "subd",
 "Rootname": "accueil.xxxxxx.fr",
 "ProxyTarget": "192.168.99.12:900",
 "UseTLS": false,
 "BypassGlobalTLS": false,
 "SkipTlsValidation": false,
 "RequireBasicAuth": false,
 "BasicAuthCredentials": [],
 "BasicAuthExceptionRules": null
}
```
v3
```
{
 "ProxyType": 1,
 "RootOrMatchingDomain": "accueil.xxxxxx.fr",
 "Domain": "192.168.99.12:900",
 "RequireTLS": false,
 "BypassGlobalTLS": false,
 "SkipCertValidations": false,
 "VirtualDirectories": [],
 "UserDefinedHeaders": [],
 "RequireBasicAuth": false,
 "BasicAuthCredentials": [],
 "BasicAuthExceptionRules": [],
 "DefaultSiteOption": 0,
 "DefaultSiteValue": "",
 "Disabled": false
}```
