### ISSUE TITLE
[ENHANCEMENTS] Add documentation on how to use the created certificates by Zaroxy ACME

### ISSUE THREAD

**Issue by markozz** [tobychui/zoraxy#105]
Hi,

With the ACME tool I created certificates for my http proxy entries. But I can't find how these certificates should be used. When I access one of my https endpoints of my http proxy, it still uses the self signed zaroxy certificate.
Could the usage of these created certificates be added to the documentation?

Apart from that really great tool!

**Comment by tobychui** [comment]
Hi @markozz 

The ACME tools is straight forward and we prefer designing the UI towards self explanatory style (i.e. user don't need to read the docs and know what to do) instead.

From what I see, this seems like a UX design issue. Can you show me the steps you create your certificates and how your http proxy is setup? Maybe I could figure out how the workflow can be further optimized.
