### ISSUE TITLE
[ENHANCEMENTS] Disable / Enable toggle for HTTP proxy rules

### ISSUE THREAD

**Issue by jerome6994** [tobychui/zoraxy#108]
Good morning

Many thanks for the work done.
I discovered zoraxy for a week and I was wondering if it was possible in the HTTP Proxy actions to make the rules active or inactive individually in order to keep the configuration despite everything.

![image](https://github.com/tobychui/zoraxy/assets/66921143/10c8a02b-b0a1-4df3-bd1c-89896523f8ae)

thanks in advance

**Comment by tobychui** [comment]
Hi @jerome6994 

Yeah sure, I was planning to add toggle feature into Zoraxy in the next release. In fact, you can already see the `"Disabled": false` settings automatically added into the config file if you are using v3.0.0.

**Comment by tobychui** [comment]
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/8c20e730-550f-4874-be26-3e43229dbe72)

@jerome6994  Here you go :D 
Will be closing this after v3.0.1 releases

**Comment by tobychui** [comment]
Added in v3.0.1
