### ISSUE TITLE
Stopping Zoraxy on status page

### ISSUE THREAD

**Issue by Morethanevil** [tobychui/zoraxy#11]
**Describe the bug**

If I try to stop zoraxy by pressing "Stop Service" it does nopt stop the service and says  "Context deadline exceeded". I need to stop zoraxy then cia CLI

**To Reproduce**

1. Go to status page
2. Click on Stop Service

**Expected behavior**

Stopping the service

**Additional context**

This only happens on my VPS. On my hoemserver, everything is normal.

**Comment by tobychui** [comment]
I wonder what is your VPS provider. From our private conversations, seems many issues we discovered are from your VPS instances (e.g. wordpress CORS, context timeout). 

I saw some similar issues on [here](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/458), which might points to the settings with some cloud service provider limiting CPU throttle or intentionally creating IO bottleneck. 

It will be nice if you could provide more information on the VPS environment and setup involved. Thanks!

**Comment by Morethanevil** [comment]
My Provider is Netcup
I have the VPS 2000

https://www.netcup.de/bestellen/produkt.php?produkt=2963

```
Processor: 8 vCores
RAM: 12 GB
320GB SSD Storage
1 G/bit network
```
The Wordpress issue is something which give me headaches :D

I tried a fresh wordpress install in LXC on my homeserver. Same problem.
Then I tried a fresh install in docker, it is very easy to test, but exact the same problem.
My homeserver is a dedicated PC.

```
Ryzen 5 5600G
16GB RAM
B550 Aorus Elite v2
100M/bit DSL with DynDNS
```

Thew issue with stopping zoraxy with the button is not that important, I have CLi when I test things :)

**Comment by Morethanevil** [comment]
Found a solution for wordpress finally...

I am using Wordpress with Apache, in the "wp-config.php" you need to put these lines after "<?php"

`if ( (!empty( $_SERVER['HTTP_X_FORWARDED_HOST'])) || (!empty( $_SERVER['HTTP_X_FORWARDED_FOR'])) ) { $_SERVER['HTTPS'] = 'on'; }`

Worked instantly
Only thing left is proper federation for matrix, I am trying out a few things :)
