### ISSUE TITLE
[ENHANCEMENTS] Option to 'Disable Chunked Encoding'

### ISSUE THREAD

**Issue by Freekers** [tobychui/zoraxy#111]
**Is your feature request related to a problem? Please describe.**
Yes, currently I receive an HTTP Error 501 when trying to use the VM console in Proxmox, while being reverse proxied via Zoraxy. [According to this thread on the Proxmox forums](https://forum.proxmox.com/threads/http-501-when-using-web-reverse-proxy-cloudflare-argo-tunnel-to-start-vm-but-stopping-vm-works.52643/page-2#post-484496), this might be due to Chunked Encoding being enabled.

**Describe the solution you'd like**
Option/Toggle to Disable Chunked Encoding, preferably per HTTP Proxy host.

**Describe alternatives you've considered**

- Switching back to Nginx Proxy Manager :(
- Not using the reverse proxied Proxmox webinterface

**Additional context**
![firefox_92ooIyaPLq](https://github.com/tobychui/zoraxy/assets/1370857/abc99be9-a2e6-4498-b886-acc0c8f136de)

**Comment by tobychui** [comment]
@Freekers I am not sure if that is related to chunked encoding. I tested the same setup in a development build of zoraxy with no chunk encoding & connected via local IP address, it still not works. 
See [here](https://github.com/tobychui/zoraxy/discussions/106) for more discussion related to proxmox and zoraxy. I will keep this open for now.

**Comment by mbah-dukun** [comment]
> @Freekers I am not sure if that is related to chunked encoding. I tested the same setup in a development build of zoraxy with no chunk encoding & connected via local IP address, it still not works. See [here](https://github.com/tobychui/zoraxy/discussions/106) for more discussion related to proxmox and zoraxy. I will keep this open for now.

I think it maybe Websocket support?

**Comment by tobychui** [comment]
Proxmox compatibility mode is now added in v3.1.0. Zoraxy will automatically force legacy HTTP connection, rewrite chunk encoding settings and perform a few more compatibility stuffs if PVE cookie is detected in the request.
