### ISSUE TITLE
[ENHANCEMENTS] add header / header change for X-Real-IP

### ISSUE THREAD

**Issue by mbah-dukun** [tobychui/zoraxy#114]
i need set x-real-ip for Zero Trust config from Cloudflare,
to set real-ip clodflare send CF-Connecting-IP for transform it to x-real-ip.
Will you add the X-Real-IP transform function from the CF-Connecting-IP Header in the future?

**Comment by tobychui** [comment]
@mbah-dukun Maybe, I just implemented an auto detection logic for CF-Connecting-IP and it shd be working for your case as well.

**Comment by mbah-dukun** [comment]
> @mbah-dukunMungkin, saya baru saja menerapkan logika deteksi otomatis untuk CF-Connecting-IP dan itu juga akan berfungsi untuk kasus Anda.

saya akan menunggu rilis berikutnya untuk update docker

**Comment by tobychui** [comment]
Feature implemented
