### ISSUE TITLE
Is it possible to add ddns services?

### ISSUE THREAD

**Issue by kotovasia5120** [tobychui/zoraxy#119]
Is it possible to add ddns services?

**Comment by tobychui** [comment]
@kotovasia5120 ddns is another rabbit hole that might need a new contributor in order for Zoraxy to add it in. You see, there are so many different ddns service provider each with different APIs. It just impossible to maintain unless there is a developer dedicated to handle that module.

**Comment by haldi4803** [comment]
Jup.
A Lot of providers.
https://openwrt.org/docs/guide-user/services/ddns/client#requirements
