### ISSUE TITLE
[BUG] Wrong SSL certificate used.

### ISSUE THREAD

**Issue by haldi4803** [tobychui/zoraxy#126]
**Describe the bug**
Wrong SSL Certificate is used.

**To Reproduce**
Install Docker container.
Get SSL cert from ACME.
Actiavte "Use TLS to serve proxy requests" in Global Settings

**Expected behavior**
Correct SSL Cert to be used.

**Screenshots**
![image](https://github.com/tobychui/zoraxy/assets/17104473/0f9c5e61-3c24-439a-8226-5158e55020e6)
![image](https://github.com/tobychui/zoraxy/assets/17104473/d6131494-f5e0-4039-9ca8-d520557d0d59)
![image](https://github.com/tobychui/zoraxy/assets/17104473/9035453a-7157-441b-b88b-cf7cfa5e584b)
![image](https://github.com/tobychui/zoraxy/assets/17104473/c4f7997a-0746-4022-8ba5-518544203550)
![image](https://github.com/tobychui/zoraxy/assets/17104473/f8cac9df-a0d7-4c2e-9954-d85e8a592352)
![image](https://github.com/tobychui/zoraxy/assets/17104473/8303736f-49b4-4727-85a9-c3265c248886)

**Browser (if it is a bug appears on the UI section of the system):**
 - OS: Windows
 - Browser Firefox, Chrome
 - Version irrelevant.

**Host Environment (please complete the following information):**
-  Arch: arm64
 - Device: Bananapi BPI-R3
 - OS: Openwrt
 - Version 23.05.0

**Additional context**
I have never found any way to select the SSL certificate. How do you select which one you use with multiple certs?

**Comment by tobychui** [comment]
That self-sign certificate is the internal fallback certificate of your site. The Server Name (host name) field is the matching rule for that certificate. As you blurred out the domain name from the list, I cannot check it for you and I will assume you have read the instruction and fill it in correctly.

Then I will need more information to see what might cause this bug.
- Are you trying to access the domain via a sub-domain?
- Is your cert a SAN cert? (A cert that covers multiple host name or contains wildcards)
- What is your default site options? Will the issue be solve if you move the cert to the "fallback certificate" field? (you can get the certificate files by digging through the conf/certs/ folder)

**Comment by tobychui** [comment]
Ok, it seems to be a wildcard certificate related issues.
Here let me introduce you the ACME module maintainer 😊 
@yeungalan 

In the mean time, can you try generate the cert using, let say one of the sub-domain, and connect through that sub-domain to see if that works?

**Comment by haldi4803** [comment]
Works fine.
use i.domain.tld, created a new Let's Encrypt Certificate via ACME, and properly used it on the correct domain.

So we end up with two issues:
A: Wildcard Certificates not working, as discussed here: https://github.com/tobychui/zoraxy/issues/79

B: Not knowing which Certificate is used for which Proxy host... it just works magically correct, most of the time.
