### ISSUE TITLE
[HOW-TO] How do I add url rewrite directives

### ISSUE THREAD

**Issue by kachmul2004** [tobychui/zoraxy#127]
How can I replicate something like this for a virtual directory? (I'm using the docker version of Zoraxy)

in nginx I would do something like this to rewrite urls 
  location /team/ {
      rewrite ^/team/(.*)$ /$1 break;
      proxy_pass_header Server;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Scheme $scheme;
      proxy_set_header USE_X_FORWARDED_HOST True;
      proxy_set_header X-Script-Name /team;
      proxy_connect_timeout 75s;
      proxy_read_timeout 300s;	      
      proxy_pass http://web:3000;
    }

**Comment by tobychui** [comment]
Hi  @kachmul2004, 

From your example, I guess you are trying to implement this rewrite logic
`rewrite ^/team/(.*)$ /$1 break;`
in which Zoraxy has that automated so you don't need to add that in manually (as soon as you have added the /team/ virtual directory). It will automatically rewrite the URL to / and proxy to the backend server. (Note that this might still got some bug around as this automation thing is new. Feel free to let me know if you encounter any issues with this :) )

**Comment by tobychui** [comment]
Closing as solved
