### ISSUE TITLE
[BUG] SMTP login options

### ISSUE THREAD

**Issue by jacojazz** [tobychui/zoraxy#129]
When using a service such as SMTP2GO, the login authentication only needs a single username and password. When trying to add SMTP settings to Zoraxy, it forces you to enter a sender domain which is used in the SMTP code below. e.g. username@domain.com, rather than allowing just username. 

**To Reproduce**
1. Go to SMTP settings
2. Enter all relevant information but not sender domain (as SMTP2GO doesn't use one)
3. Click save settings
5. See error

**Expected behavior**
Login is allowed, and test email/forgotten password emails are sent.

**Screenshots**
```
//Login to the SMTP server
	auth := smtp.PlainAuth("", s.Username+"@"+s.Domain, s.Password, s.Hostname)
	err := smtp.SendMail(s.Hostname+":"+strconv.Itoa(s.Port), auth, s.SenderAddr, []string{to}, msg)
	if err != nil {
		return err
	}

return nil
```

![image](https://github.com/tobychui/zoraxy/assets/4930086/6bee3953-ea9c-42b2-ab28-db880e5d0ee0)
![image](https://github.com/tobychui/zoraxy/assets/4930086/a43e4500-8c7a-4d9a-b9a6-5b869b6ddf88)

**Browser (if it is a bug appears on the UI section of the system):**
 - OS: Windows
 - Browser Chrome

**Host Environment (please complete the following information):**
-  Arch: linux x86
 - Device: Dell Poweredge 410
 - OS: Docker via portainer on Ubuntu
 - Version 22.06

**Comment by tobychui** [comment]
Hi @jacojazz , you mind checking out the new v3.0.3 branch and see if it is working in your case? As I personally use gandi and gandi usually require the domain field. I have removed the check and validation for the Domain field (now it can be empty), if it works with your SMTP service provider, please let me know so I can work on the UI optimization.

**Comment by jacojazz** [comment]
Hi @tobychui, that worked like a charm, thank you!
