### ISSUE TITLE
[ENHANCEMENTS]Show LAN IP as "LAN" and not some other countries

### ISSUE THREAD

**Issue by haldi4803** [tobychui/zoraxy#131]
**Is your feature request related to a problem? Please describe.**
It seems like the LAN IP is shown as Australia[AU]. Ist that just the first pick? Or does it randomly Assign when it's unsure?

**Describe the solution you'd like**
A Filter that filters out LAN IP's like 192.168, 172.16 -172.31, 10. an marks them as LAN before doing a Country Search Lookup.

**Additional context**
![image](https://github.com/tobychui/zoraxy/assets/17104473/2dcdc1ca-8d9f-49c1-a31c-203e39990399)

**Comment by Famku** [comment]
maybe cloudflare DNS [1.1.1.1] - located in Australia

**Comment by daniel-l** [comment]
Not using Cloudfare here - same result. I'm using Zoraxy locally only, there's no access from outside my LAN. IPs in the range 192.168.0.0/24 get lists as australian origin

**Comment by tobychui** [comment]
You know what, I didn't expect people using it as an internal service proxy so I didn't bother to check for if the incoming request is from LAN while loading the statistics. But yeah, it should be an easy fix 👍🏻

**Comment by haldi4803** [comment]
There are a lot of services that need proper SSL encryption.
Even if only used inside the LAN for oneself :)

**Comment by daniel-l** [comment]
> There are a lot of services that need proper SSL encryption. Even if only used inside the LAN for oneself :)

I'm not even using it for/with SSL; I just do not want to remember IPs and ports and do not want to maintain some dashboard with links to my services ^^
