### ISSUE TITLE
[BUG] Proxy rules requiring TLS don't connect after 3.0.3

### ISSUE THREAD

**Issue by jacojazz** [tobychui/zoraxy#139]
**Describe the bug**
After the update to 3.0.3, it looks like all rules that have the "Require TLS" box ticked, aren't able to connect. For services like Portainer, I can remove the tickbox, and the server still responds with "Client sent an HTTP request to an HTTPS server." so the service is running properly. Just as soon as the tickbox is selected, I get a 404. 

**To Reproduce**
1. Create Proxy rule to https accessed service such as portainer.
2. Ensure "Requires TLS" checkbox is selected.
3. Ensure rule is active.
4. Navigate to service using subdomain, get a 404 error.

**Screenshots**
![Rule](https://github.com/tobychui/zoraxy/assets/4930086/d6690788-d1cf-4882-9ba9-a7fc8baae5fb)

**Browser (if it is a bug appears on the UI section of the system):**
 - OS: Windows 11
 - Chrome

**Host Environment (please complete the following information):**
-  Arch: linux x86
 - Device: Dell Poweredge Server
 - OS: Ubuntu running docker through portainer

**Additional context**
I will say that doing the test for the fix for #129, this problem didn't arise.

**Comment by Morethanevil** [comment]
Can you try to remove all "Require TLS" boxes and use the global setting? For external services I use the global setting, see screenshot below

![Screenshot_20240430_105608](https://github.com/tobychui/zoraxy/assets/110860055/151e0a02-7985-4626-b8e1-23bb9e3bd850)


Does this help?

**Comment by jacojazz** [comment]
I already had these settings enabled, but I went ahead and removed all "Require TLS" boxes, but from the services that have https only access such as portainer, I'm now getting the http response: 

![image](https://github.com/tobychui/zoraxy/assets/4930086/e05c512d-4bfb-4f54-b220-e111e13404b8)

**Comment by tobychui** [comment]
@jacojazz I am unable to reproduce your issue with a self sign cert and arozos (listening to port 8443, with HTTP disabled) running in localhost
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/9dfc0085-1442-4093-9188-d2e56337b1e2)

ArozOS is also written in golang and if there is an error sending to the HTTP server, the same error will show up. The following is an example of me manually triggering this error with direct http to :8443 access
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/eda0941c-8b86-4541-a0b5-e1eab8375cf3)

I setup the rule like yours and I am seeing no problem regarding sending HTTP request to HTTPS server error
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/cf974979-2d40-4b91-ba2d-9156cfbef8e8)

**Comment by Morethanevil** [comment]
I never used "Require TLS" in addition, just the global setting and the force HTTPS redirect. Zoraxy listens on port 443

The proxy rule is set to the container HTTP port. HTTP because TLS is done by Zoraxy. Do not use the HTTPS in the proxy rule for portainer!

Can you try port 9000 for portainer in your rule?

**Comment by NeoMod** [comment]
> Can you try to remove all "Require TLS" boxes and use the global setting? For external services I use the global setting, see screenshot below
> 
> ![Screenshot_20240430_105608](https://private-user-images.githubusercontent.com/110860055/326736564-151e0a02-7985-4626-b8e1-23bb9e3bd850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NzgzMTgsIm5iZiI6MTcxNDU3ODAxOCwicGF0aCI6Ii8xMTA4NjAwNTUvMzI2NzM2NTY0LTE1MWUwYTAyLTc5ODUtNDYyNi1iOGUxLTIzYmI5ZTNiZDg1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQxNTQwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2Q5MjQ5OWQ3ZTUyZjBkZjhmYTU0OTg2M2JjYzVhMWZkNDUzZDg4NTQ2MWZlMTk2OTVlNzZkOTEzNmM0NTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zS2BfyIMXG6QdXxW6hQCVsNr4I2cZcMpDbQQaKq_z8Q)
> 
> Does this help?

Thank you! Coming from NPM I missed this section inside the configuration and struggled too. Works great now.

@jacojazz 

For Portainer, unless you configure a valid SSL certificate *inside portainer itself* you may want to use the "Skip Verification" toggle in Zoraxy: doing so, the proxy manager will ignore the "certificate warning" and reach portainer on port 9443.

(as explained pretty much in the tip under the checkbox, you are just instructing zoraxy to skip verification of the self-signed certificate generated and used by portainer while connecting locally. From the outside, if everything else is configured accordingly, you will tunnel trough https using the provided/generated certificate)

<img width="214" alt="image" src="https://github.com/tobychui/zoraxy/assets/13747261/780d2637-6df6-4e6a-b8e0-114d6bb88c24">

**Comment by tobychui** [comment]
Closing this due to inactive and the issue mostly cause by docker networking / user error. 
For future visitors: Please check [this](https://github.com/tobychui/zoraxy/wiki/Zoraxy-in-Docker-with-Portainer-and-Nginx-as-examples) wiki page on how to correctly setup Zoraxy with Portainer
