### ISSUE TITLE
Backup and Restore functionality

### ISSUE THREAD

**Issue by Morethanevil** [tobychui/zoraxy#14]
A great feature would be "Backup and Restore" of the entire Zoraxy configuration. If a user wants to change the server, or changes from docker to hostinstallation and vice versa, they only need to install Zoraxy and import their backupfile.

It would make sense to place this in the Utilities tab. A click on backup would then backup all virtual directories, subdomain proxys and so on, store it in a zip file, which is automaticly downloaded.

To do a restore the configuration this file only needs to be uploaded, and then a restart of Zoraxy is performed.
With this feature it would not matter anymore on which platform Zoraxy is running, it coukd be changed very easily without data loss.

**Comment by tobychui** [comment]
I don't think this is necessary, as Zoraxy itself is a portable app. What you need to do is just copy all files from your Zoraxy root and paste it in a new machine.

If you are changing host's CPU architecture (e.g. switching from arm64 to amd64 Linux ), you will only need to swap out the binary file and you are ready to go :D

**Comment by Morethanevil** [comment]
Zoraxy root is /zoraxy or /zoraxy/src?

Will try this later and put it in the Wiki

**Comment by Morethanevil** [comment]
Made a wikipage with a short tutorial. Closing this
