### ISSUE TITLE
[ENHANCEMENTS] UDP Tunneling / Proxy

### ISSUE THREAD

**Issue by DerLeole** [tobychui/zoraxy#147]
**Is your feature request related to a problem? Please describe.**
Zoraxy allows tunneling TCP connections similar to Stream Hosts in NginxProxyManager.
The screenshots demonstrate one of its main use cases with the example of a Minecraft game server.
However some Games (or in my case a specific mod for MC) require a UDP connection which does not seem to be possible at the moment.

**Describe the solution you'd like**
Add a feature that paralells how the TCP Proxy already works, but for UDP connections instead.

**Describe alternatives you've considered**
Refactor the TCP Proxy feature into a general "Stream Proxy" feature that allows for either UDP, TCP, or both for the specific connection.
This is probably the cleaner and prefered method.

Thank you very much for your work on this.

**Comment by tobychui** [comment]
The TCP proxy function was ~~stolen~~ forked from this repo
https://github.com/cw1997/NATBypass

As the original repo didn't support UDP yet (it is in the to-do list), we need to wait for the project to be updated in order to integrate it into Zoraxy.

**Comment by mflagler** [comment]
Considering the last commit to NATBypass was 6 years ago, I wouldn't hold my breath that this will ever happen.

**Comment by tworth04** [comment]
this one seems to be more actively maintained...https://github.com/yusing/go-proxy?tab=readme-ov-file#provider-kinds

**Comment by tobychui** [comment]
I have manually added UDP proxy function into the original NATBypass code base. I am still testing it right now and I guess this feature should be ready in 1 or 2 releases.
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/e10e5d81-e323-4282-837e-c135f6d83e9d)

**Comment by DerLeole** [comment]
Man that's some great work!
Thank you so much.

**Comment by tobychui** [comment]
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/cb3b58b9-551a-482f-bb2f-0c6bf5edf1a0)
Feature added in v3.0.6
