### ISSUE TITLE
Start automatically after boot

### ISSUE THREAD

**Issue by Arnau97** [tobychui/zoraxy#148]
Hello, I just tested this proxy and seems really good! I only have one question, how can I make it start at the moment my ubuntu pc boots? Because I restarted my pc and I need to manually start it

**Comment by Morethanevil** [comment]
You need to create a systemd service for this. There is guide in the wiki ☺️

https://github.com/tobychui/zoraxy/wiki/FAQ---Frequently-Asked-Questions#create-a-systemd-service-for-zoraxy

**Comment by PassiveLemon** [comment]
If you are using Docker, you need to specify either restart `always` or `unless-stopped` for it to start upon boot (If Docker is configured to start upon boot). Using the latter option will only start the container after boot if it wasn't manually stopped before shutting down.

**Comment by Arnau97** [comment]
Thanks! And sorry for not looking the wiki before doing this post

**Comment by Morethanevil** [comment]
If your problem is solved, you can close this issue ☺️
If you have more questions, you can take a look at the discussion page


@PassiveLemon 

Maybe you can add the restart policy in your docker-compose file to prevent this issue for the docker version 🤔
