### ISSUE TITLE
Add version info to footer or even better add apt repository

### ISSUE THREAD

**Issue by Shotte** [tobychui/zoraxy#160]
@tobychui 

Please add version info to footer. This makes it easier to identify the currently running version and if an update makes sense.

Even better: add an apt repository for automatic update. This would be really great.

**Comment by tobychui** [comment]
You can find the version information under Utilities > System > Version
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/1a029abf-993c-46b4-b668-220fa81a224a)

Currently there are no plan for apt-repo support as: 
1. Zoraxy is released as a binary. A simple crontab (with ./zoraxy --version for version check) is enough to keep everything updated
2. We don't have enough contributors to catch up with all the feature requests, not to mention maintaining a new releases location

If you are interested in helping us to maintain the Zoraxy apt-repo, feel free to let me know so we can discuss further about this.

**Comment by tobychui** [comment]
Feature added in v3.0.6
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/7355c5ce-310a-4390-af10-35d919841ac7)
