### ISSUE TITLE
[ENHANCEMENTS] Reduce the size of the artifact

### ISSUE THREAD

**Issue by tonyho** [tobychui/zoraxy#165]
The ELFs at release are too big(>100M), any plan to reduce it? 
Maybe split to several versions: small version with specific function only, Full function version

As the embedded device would have contrained flash storage.

**Comment by tobychui** [comment]
No, but you can use [upx](https://upx.github.io/) to compress the binary executables (ELFs). 

Older version of Zoraxy without DNS challenge support is much smaller, but if we separate this function as plugin like what Caddy does, then user will need to recompile Zoraxy themselves to enable a certain DNS challenge supplier which is not beginner friendly.

By the way, what embedded device you are testing with Zoraxy? I tried Zoraxy with Raspberry Pi 2 with 8GB SD card, still get around 3GB space left without any issues.
