### ISSUE TITLE
[ENHANCEMENT] Add TCP Proxy auto start option after reboot ( docker )

### ISSUE THREAD

**Issue by mbah-dukun** [tobychui/zoraxy#169]
**Describe the bug**
TCP Proxy wont start after reboot / restart container

**To Reproduce**
Restart Docker Container

**Expected behavior**
automatically starting TCP Proxy

**Comment by tobychui** [comment]
This is not a bug. It just not support TCP proxy auto start after reboot.

**Comment by tobychui** [comment]
Feature added to Stream Proxy (now support both TCP and UDP proxy) in v3.0.6
