### ISSUE TITLE
[ENHANCEMENTS] Websocket support (i think?)

### ISSUE THREAD

**Issue by danmed** [tobychui/zoraxy#17]
When i use Zoraxy to reverse proxy proxmox (for example) the consoles on the vm's don't work.

I believe this is down to web sockets though i could be way off..

**Comment by Morethanevil** [comment]
Chrome based Browser or Firefox? Does private mode work with addons disabled? 

What does happen when you open the console?

You could try it with Firefox portable. If it works there, then it has something to do with your Browser 🤔

**Comment by tobychui** [comment]
By default all the proxy endpoints (vdir or subdomain) supports websocket reverse proxy automatically by checking the UPGRADE headers. This should be an issue with the browser you are using or if you are using another reverse proxy in-front or behind Zoraxy that has invalid configs.

**Comment by danmed** [comment]
> By default, all the proxy endpoints (vdir or subdomain) supports websocket reverse proxy automatically (by checking the UPGRADE headers). The issue you are having here should be a problem with the browser you are using. In the case where you are using another reverse proxy in-front or behind Zoraxy, there might be invalid config that altered the UPGRADE header in the request.

Interesting.. whilst i'm not in the know enough to argue with you.. it's the same browser i use when i use NPM.. (but then maybe that's the issue).. let me bring up a clean browser and ill come back to you.

**Comment by PMFRTT** [comment]
Hi, I'm having a similar issue when trying to connect from my phone to my unifi controller via the app through zoraxy. It seems I cannot access it through zoraxy. It worked when is used NPM and also works when trying to connect via IP:PORT, skipping over zoraxy.

Here is a screenshot of the issue in App:
![Screenshot_20230701_221539~2.jpg](https://github.com/tobychui/zoraxy/assets/37709302/3eb79c53-6346-421d-a777-c2b8a4a0858e)

Currently not at home, will add logs of zoraxy as soon as I can.

**Comment by tobychui** [comment]
@PMFRTT You sure this is a Websocket issue? I have done a simple google search which leads me to this [post ](https://community.ui.com/questions/Up-to-date-NGINX-config-for-reverse-proxying-Unifi-Controller/ee3980b1-161f-4469-9e39-26f680542357) regarding the nginx config for unified.

As the config comments says
```   # The lack of '/' at the end is significant. ```
I guess this might be an issue where the unified app is calling to an API without tailing slash while zoraxy is trying to patch the tailing slash for you. If you confirm this is not a websocket issue, please open a new issue for this problem and I will see how can I help debug it further.  Thanks for reporting a new issue!

**Comment by tobychui** [comment]
Closing as this cannot be reproduced. (Please let me know to re-open this if there are further related issues)
