### ISSUE TITLE
Unable to create certificates [BUG]

### ISSUE THREAD

**Issue by boehamian** [tobychui/zoraxy#172]
**Describe the bug**
When I go to create a certificate via lets encrypt I get the following error 
Error: one or more domains had a problem: [SUB DOMAIN NAME] acme: error: 400 :: urn:ietf:params:acme:error:connection :: "MY EXTERNAL IP": Fetching http://SUB DOMAIN NAME/.well-known/acme-challenge/54ar6kB95vfv8QalTB7cQnKGugUCNWqAifE2B1u6K7o: Timeout during connect (likely firewall problem)

**To Reproduce**
1. Go to 'Creat Proxy Rules'
2. Type in matching keyword/Domain
3. Type in Target IP with port
4. Accept yes when the prompt "request a SSL certificate for this sub domain pops up. 

If I try and go through the acme wizard it for some reason is unable to be reachable from public IP. My router was setup for NGINX proxy manager and worked fine before this. 
**Expected behavior**
Expected it to grab a certificate from lets encypr without any errors

**Screenshots**

**Browser (if it is a bug appears on the UI section of the system):**
 - OS: windows
 - Browser edge
 

**Host Environment (please complete the following information):**
-  Virtual machine running ubuntu 22.04
- creating instance through portainer 

 Error: one or more domains had a problem: [nextcloud.outbacknerd.party] acme: error: 400 :: urn:ietf:params:acme:error:connection :: MY PUBLIC IP: Fetching http://SUB DOMAIN NAME/.well-known/acme-challenge/54ar6kB95vfv8QalTB7cQnKGugUCNWqAifE2B1u6K7o: Timeout during connect (likely firewall problem)

**Comment by boehamian** [comment]
side note letsdebug.net does not have a problem with reaching my sub domain.

**Comment by boehamian** [comment]
next update. Forgot that nginx was still configured in my internal DNS record. Had removed it now I get ACME error 403 when requesting a certificate. When using the ACME wizard the server is still unable to reach my public IP. 
![image](https://github.com/tobychui/zoraxy/assets/153267181/76bb24b7-aca4-4ae0-8427-2b7d191db35d)

**Comment by tobychui** [comment]
It is mostly your (docker?) networking issues and without including your subdomain in the issue, basically there is nothing we can help. 

I should add a issue tag for "user network issues" later.

**Comment by yeungalan** [comment]
And, the error message seems to have leaked your IP address. You may want to remove it from the correspondence to avoid any network attack

**Comment by boehamian** [comment]
https://github.com/tobychui/zoraxy/issues/172#issuecomment-2130789623
thanks, have mended a few things

**Comment by boehamian** [comment]
> And, the error message seems to have leaked your IP address. You may want to remove it from the correspondence to avoid any network attack
@
Hi mate, sorry for changing a few things computer is playing funny buggers. 

I have changed a few things on the settings side on my router and DNS and now get error 403. 

M

> And, the error message seems to have leaked your IP address. You may want to remove it from the correspondence to avoid any network attack

thanks, have mended a few things

**Comment by boehamian** [comment]
> It is mostly your (docker?) networking issues and without including your subdomain in the issue, basically there is nothing we can help.
> 
> I should add a issue tag for "user network issues" later.

thanks for the prompt reply. A few bits of information to add. 

my sub-domain is nextcloud.outbacknerd.party. 
The lts encrypt debug tool passes 
![image](https://github.com/tobychui/zoraxy/assets/153267181/4a22855a-63da-457b-ab7e-1e55cc56faa2)

Out of curiosity, I am using portainer to create the instance of zoraxy. My config is below. Are you able to tell me if this config is wrong or am I missing something for this? I have created the zoraxy network manually in portainer. 
services:
  zoraxy:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    restart: unless-stopped
    ports:
      - ZORAXY IP:80:80
      - ZORAXY IP:443:443
      - ZORAXY IP:8005:8000/tcp
    networks:
      zoraxy:
    volumes:
      - ./config:/opt/zoraxy/config/
    environment:
      ARGS: '-noauth=false'

networks:
  zoraxy:
    external: true


My apologies, relatively new to all this. /
![image](https://github.com/tobychui/zoraxy/assets/153267181/15c9dc8c-1432-40a2-938d-e1c6a3ef1e3a)

**Comment by tobychui** [comment]
@boehamian Your portainer setup looks normal. The issue I guess is related to DNS and you are not pointing the DNS / domain to your Zoraxy instance. If you are new to networking, I recommend using the native version of Zoraxy instead of the dockerize version. With the dockerized version, a lot of automatic debug and sniffing features are missing.

**Comment by boehamian** [comment]
> @boehamian Your portainer setup looks normal. The issue I guess is related to DNS and you are not pointing the DNS / domain to your Zoraxy instance. If you are new to networking, I recommend using the native version of Zoraxy instead of the dockerize version. With the dockerized version, a lot of automatic debug and sniffing features are missing.

Thanks mate, I have managed to fix the issue. I guess the take away from this is double check everything when you aren't running off lack of sleep and alcohol. I missed the fact my domain registrar still had put their name servers back in the list along with my clouddns.net name servers. thanks for your help.
