### ISSUE TITLE
[ENHANCEMENTS] - Access Control UI/UX

### ISSUE THREAD

**Issue by jerome6994** [tobychui/zoraxy#176]
Good morning

Great work these last updates the little on/off button on the HTTP Proxy and the consideration of OVH wildcard certificates 

In terms of user interface, is it possible at the level of access control blacklist, whitelist etc... to select several countries at the same time to put them in the list? For example CTRL (cmd) + Mouse selection

Is it also possible to copy and paste a rule to define another on the same basis?

Another point is it possible to put for example USA on blacklist but Alexa IPs on whitelist without this blocking them? today if the country is blacklisted then all the IPs are blocked even if there are whitelisted IPs?

thanks in advance

Jerome

**Comment by tobychui** [comment]
@jerome6994 I guess you get confused on how whitelist and blacklist works in Zoraxy. 
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/112a6c56-eca9-47bd-bd73-66965781afc4)

As written in the whitelist title description: 
> Whitelist has lower priority than blacklist if both whitelist and blacklist are enabled
Tips: You can use blacklist to fine tune whitelist coverage

You should whitelist the country you want to have access and use blacklist to block other region. In your use case mentioned, you should add Alexa IPs in the whitelist (and your own country / ips if needed) and do not need to enable blacklist. That way, all access from USA will be blocked except Alexa IPs.

**Comment by barto95100** [comment]
IF I understan, IP in whitelist just this IP is authorized and all other is blacklist natively by zoraxy ?

**Comment by jerome6994** [comment]
ok I think I understand the usage a little better.

But regarding the multiple selection in the drop-down list with a CTRL + Mouse Selection then then added, is it possible to have it rather than doing it country by country?

**Comment by tobychui** [comment]
@jerome6994 Yes, I can change the selection to multi-selection dropdown. But generally speaking, unless you are doing a migration (in which you should just go to the `conf/` folder and edit the json files directly), if you are in a situations where you need to blacklist / whitelist a lot of countries, you are using it wrong. You sure you are using the filter correctly or you still need more assistants in setting up your access filter?

**Comment by tobychui** [comment]
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/431cfef2-366d-4631-ab1e-f85bdb04af0a)
Multi-select in access control country list added in v3.0.6
