### ISSUE TITLE
[HELP] Connexion timeout

### ISSUE THREAD

**Issue by antipiot** [tobychui/zoraxy#178]
First of all, thanks for your work on Zoraxy! It looks really great! amazing job.

**What happened?**
Some of my services seems to "timeout"

**Describe what have you tried**
I'm using nextcloud and navidrome
About Nextcloud: 
I backup my phone to it every day, at night.
The backup process takes about 30 minutes but fails since i've switched to Zoraxy.
In backup error Log i can see a "timeout" error.

On navidrome the server say's it's"offline" but is browsable and music can be played

I think both issue are related to a timeout or something like that.

*Describe the networking setup you are using**
Latest Zoraxy Version in docker on a debian host

**Additional context**
Thoses configs are in my old NPM docker container which, as far as i can remember, does not have the same issues:
proxy_read_timeout 30m;
proxy_buffering        off;
proxy_request_buffering    off;

Can thoses settings be translated to Zoraxy?

Regards

**Comment by tobychui** [comment]
Hi @antipiot 
First of all, `proxy_read_timeout 30m;` is not a reasonable options in the first place for web server. But let say you needs it in your setup for some reasons.

Currently Zoraxy don't have an option for manually setting the read-timeout value and using the default value in go-http-client. For `IdleConnTimeout` (aka Keep-Alive), it is set to 30 seconds but if you are constantly sending data between your server and Zoraxy, this should not kicks in.

Might I know what apps you use to backup your phone and what connections the app use to make such backup? Generally speaking, if there is active data transfer between your phone and Zoraxy, Zoraxy will not close the connections and cause the timeout issue. So there might be something weird happening 🤔

**Comment by antipiot** [comment]
Hi @tobychui !
Thanks for your time and answer.

I cant remember accurately why i've put thoses options in NPM, but it's surely not for no reason.

I use an application called "Folder Sync" connected using https to Nextcloud
The backup size is usally around 12 GB transferred at 15 MB/s rate

**Comment by tobychui** [comment]
@antipiot  can you tell me a bit more on how you setup your app (like are you using WebDAV? or what kind of protocol / url endpoint in NextCloud is used for the sync?) As this seems like a paid app and I don't think I will get it just for testing, I will need another way to reproduce your issues and see if this is a bug or a problem cause by other factors.

**Comment by antipiot** [comment]
@tobychui 
The app is free (with ads)

I guess this capture of the account connexion page may help you
![image](https://github.com/tobychui/zoraxy/assets/26579988/326c96bf-1013-42f9-903f-e48ffda5c1b4)

And here's the error after 24 minutes of backups
![image](https://github.com/tobychui/zoraxy/assets/26579988/d21d817d-ad63-40f7-8659-f28995bfd093)

**Comment by tobychui** [comment]
@antipiot Have you tried disable "Expect-continue"?
According to this doc here
https://hc.apache.org/httpclient-legacy/apidocs/org/apache/commons/httpclient/params/HttpMethodParams.html#USE_EXPECT_CONTINUE

>'Expect: 100-continue' handshake should be used with caution, as it may cause problems with HTTP servers and proxies that do not support HTTP/1.1 protocol. 

Zoraxy is proxying with HTTP2, maybe that is the problem?

**Comment by antipiot** [comment]
@tobychui I can surely try to disable it and see! Thanks for the hint!
So NPM support both http 1 and 2.

i'll take this opportunity to give you more informations about my "navidrome" problem aswell.
When everything is OK, my navidrome show's and with it's uptime like this:
![image](https://github.com/tobychui/zoraxy/assets/26579988/60f38fbe-6676-4c40-a63b-be35e47676e4)

ill edit this post later with a capture of the error :)

**Comment by tobychui** [comment]
@antipiot That bug in server uptime is probably a minor one from the app that the developer didn't expect you to switch proxy server mid-way of it is doing something. As soon as it is working, it should be fine. 

Also, after you changed the setting, can you also keep track on when the error shows (i.e. how many minutes the connection is working continuously without timeout). From the duration I might be able to figure out the issue here.

**Comment by antipiot** [comment]
@tobychui

About Navidrome:
Seems not  because it goes back to offline mode right after the scan:
![image](https://github.com/tobychui/zoraxy/assets/26579988/1c9be161-7155-4117-aaa8-4b3f0c49a006)

About Nextcloud / foldersync
Will report back after some times, if i fire a backup now, i have no big delta to trigger the timeout.
