### ISSUE TITLE
[BUG] Whitelist not working when using CIDR or wildcard IPs

### ISSUE THREAD

**Issue by PMFRTT** [tobychui/zoraxy#18]
**Describe the bug**
Whenever i try to whitelist local IP-Ranges it doesn't work. When visiting a Page, i always get the following error:
![image](https://github.com/tobychui/zoraxy/assets/37709302/f51ea70e-e2d7-4546-b294-88c7b6c1e77f)

When whitelisting the fixed IP of the Client i'm visiting from, it works perfectly.

**To Reproduce**
1. Go to 'Access Control'
2. Click on 'Whitelist'
3. Scroll down to 'IP Whitelist'
4. Add IP-range via CIDR or wildcard
5. Visit proxied Webpage 
6. See error

**Expected behavior**
When adding a CIDR range, IP-Adresses in that range should be able to visit proxied pages

**Host Environment (please complete the following information):**
-  Arch: amd64
 - Device: Docker Container with Zoraxy v2.6.2

**Comment by tobychui** [comment]
Thanks for the bug report! Let me look into it further this weekend.

**Comment by tobychui** [comment]
Fixed in latest commits
