### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by bwcxyk** [tobychui/zoraxy#180]
Does it support the same as nginx reverse proxy
```
server {
        listen 30001;
        server_name localhost;
	proxy_intercept_errors on;
        location / {
            proxy_pass http://a.example.com;
        }
}
```

**Comment by tobychui** [comment]
@bwcxyk  Zoraxy is not based on nginx, so you can't just migrate the config from nginx into Zoraxy without modifications. But the functions described above is achievable in Zoraxy. Read [here](https://github.com/tobychui/zoraxy/wiki/Getting-Started) for more information on how to get started.

**Comment by bwcxyk** [comment]
I can't forward an internal domain to a port

**Comment by tobychui** [comment]
@bwcxyk You need to set Zoraxy inbound port to 30001 and proxy target set to your internal domain, assuming your DNS setup is correct with the host running Zoraxy. If you need help, open a help template issue instead of a enhancement request.

**Comment by bwcxyk** [comment]
> @bwcxyk You need to set Zoraxy inbound port to 30001 and proxy target set to your internal domain, assuming your DNS setup is correct with the host running Zoraxy.

That's probably not what I want, I'll forward multiple internal domains for easy incoming port mapping to the extranet

**Comment by tobychui** [comment]
@bwcxyk Interesting networking setup, are you from China? (if yes, you can just use Chinese. I can read it lmao) 
Have you tried the TCP proxy and forward another port back to the `localhost` listening port (e.g. 80 / 443)? Without more information about your use case, I am not sure what you want to do and probably can't give you any good suggestions.

**Comment by bwcxyk** [comment]
> @bwcxyk Interesting networking setup, are you from China? (if yes, you can just use Chinese. I can read it lmao) Have you tried the TCP proxy and forward another port back to the `localhost` listening port (e.g. 80 / 443)? Without more information about your use case, I am not sure what you want to do and probably can't give you any good suggestions.

目前我这边会使用 nginx 将内部域名转发到不同的端口，方便在路由器上面进行端口映射。
尽管使用翻译软件，不过在 GitHub 上使用英语更适合😂

**Comment by tobychui** [comment]
@bwcxyk 那你應該應該用 nginx。Zoraxy 的設計是給不想用 docker 的人有一個 nginx proxy manager 的替代品，本身並不是設計來代替 nginx 的。不過如果你有興趣加入 multi-inbound port 支援，歡迎 PR~

You should use nginx. Zoraxy is designed as an alternative choice for people needing a reverse proxy solution without Docker, and is not designed to be an alternative to nginx. If you are interested in adding support for the multi-inbound port support, PRs are welcomed.

**Comment by bwcxyk** [comment]
是的，nginx添加四层代理已经满足使用了。我没有使用过 nginx proxy manager 也不太需要使用可视化管理😂
