### ISSUE TITLE
[ENHANCEMENTS] Add Strato dns challenge

### ISSUE THREAD

**Issue by CryPt00n** [tobychui/zoraxy#182]
**Is your feature request related to a problem? Please describe.**
No, just am improvement for german people

**Describe the solution you'd like**
Strato dns challenge would be great when added for lets encrypt. Dont know if it helps, but there is one available for nginx proxy manager too (https://github.com/Buxdehuda/strato-certbot)

**Describe alternatives you've considered**

**Additional context**

**Comment by tobychui** [comment]
The DNS challenge function in Zoraxy is powered by [lego](https://github.com/go-acme/lego). 
If the supplier you want doesn't exists in lego, then it will not exists in Zoraxy. I would suggest you to open a feature request over the lego repo and ask for "Strato dns" support. to be added in their library.
