### ISSUE TITLE
[BUG] Unable to keep activation state for Redirect - Regular Expression

### ISSUE THREAD

**Issue by WalterJZ** [tobychui/zoraxy#199]
Hello!

The setting for Redirection -> Advance Settings -> Enable Regular Expression Support is always disabled after reboot.

What should I do to ensure that the setting remains active even after restarting the operating system?

The operating system is Debian 12.5
I use the native installation without docker.
Zoraxy version is 3.0.6

Thank you in advance. 
Kind regards

**Comment by tobychui** [comment]
I found this is actually a typo in the database write function

https://github.com/tobychui/zoraxy/blob/fc88dfe72edd947cf00f31256a5479b63380082b/src/redirect.go#L94

Changing this line from `Redirect` to `redirect` and build from source again will fixes this issue.
(i.e. new line shd looks like this)
```
err = sysdb.Write("redirect", "regex", enableRegexSupport)
```
If you don't know how to build Zoraxy, you can wait for the next release.

**Comment by WalterJZ** [comment]
Thank you very much! The problem is solved.
