### ISSUE TITLE
[BUG] Antivirus think it is a malware due to remote ssh execution

### ISSUE THREAD

**Issue by yeungalan** [tobychui/zoraxy#20]
**Describe the bug**
I would like to bring to your attention that zoraxy, is being misidentified as malware by various antivirus software. 

Here is the virus scanning report.
https://www.virustotal.com/gui/file/3cb5a6b1434ab31b841dceb81f432d6654e04e7a416f0550179311f30d2dbaac
![image](https://github.com/tobychui/zoraxy/assets/12872405/02918595-843b-43d7-bbc4-1d00e707c971)

**Host Environment (please complete the following information):**
- Windows x64

**Comment by Morethanevil** [comment]
I uploaded it to virustotal.com 7 scanners show this result. 

https://www.virustotal.com/gui/file/3cb5a6b1434ab31b841dceb81f432d6654e04e7a416f0550179311f30d2dbaac/detection

**Comment by tobychui** [comment]
Blame Windows for it 🫠
(Serious solution: Just whitelist it manually, build it yourself on your own server or sign it yourself. I don't think this issue worth fixing)
