### ISSUE TITLE
[HELP] certificat ssl on stream proxy

### ISSUE THREAD

**Issue by barto95100** [tobychui/zoraxy#205]
If thé stream proxy used to forward port that necessary the ssl (pop3/imap) it's possible zoraxy and the certificat on requiest ? 

if yes, how can i do that ?

**Comment by tobychui** [comment]
No. It is TCP / UDP proxy. TLS is on top of that and pop3/imap are out of the scope of HTTP reverse proxy. 
If you need such feature, feel free to implement it yourself and create a pull request 👍🏻
