### ISSUE TITLE
[ENHANCEMENTS] Disable X-Real-IP

### ISSUE THREAD

**Issue by mbah-dukun** [tobychui/zoraxy#207]
Hello, i have problem when access local web app because access from public. This app need local network from access. I think this can be add disable Header X-Real-IP, or it can be configured from custom header?

**Comment by tobychui** [comment]
You can go to custom header and remove it by choosing the `Zoraxy >> Origin` and `Remove Header` options
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/203df4c1-0761-4e0a-b982-6525e680ec20)

![圖片](https://github.com/tobychui/zoraxy/assets/24617523/adb07cf9-55b3-4101-9253-c521dda3742b)
