### ISSUE TITLE
[HELP] Jellyfin Android TV won't connect 

### ISSUE THREAD

**Issue by AzAel76** [tobychui/zoraxy#214]
Can anyone share the custom headers required for the Android TV Jellyfin app to connect to a remote instance?

All other clients work fine it just seems to be the ATV app that chokes.
Works perfectly with npm.

**Comment by Morethanevil** [comment]
Maybe related to this issue? #163

**Comment by AzAel76** [comment]
I think undoubtedly it does. But unfortunately I'm one of those people that Would just look for a working example and literally copy paste. 
This means that what I'm really asking is how to translate from commonly available examples to what I need to enter into Zoraxy to achieve the same result.

**Comment by AzAel76** [comment]
Just wanted to update this. 
It was NOT a header issue and further research lead me to discover that a full chain public cert file was required as the Jellyfin ATV requires an intermediate cert. 
I am still getting web socket errors though

 `websocketproxy: couldn't dial to remote backend url websocket: bad `handshake`

**Comment by tobychui** [comment]
@AzAel76 I don't use Jellyfin so there isn't much I can suggest or recommend you trying. But from the error message, it sounds like there is a connection issues to your backend from Zoraxy. WebSocket proxy is switched automatically in Zoraxy so it mostly not a protocol switching issues but a config / networking one?

Can you show us how you setup Jellyfin proxy in your Zoraxy?

**Comment by Morethanevil** [comment]
Can you try to check "Skip Websocket origin check"? It is in the settings of your HTTP Proxy 
![Screenshot_2024-06-22-15-18-37-30_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/tobychui/zoraxy/assets/110860055/ef1ddacf-8dcc-4245-abdf-a62d15c69485)


Maybe this helps

**Comment by Kirari04** [comment]
Hey guys
I personally use Jellyfin with Zoraxy (with Docker) and didn't have to configure any additional things to get it working (using it on Web, Android Phone (Findroid) and Apple TV (swiftfin)).
There might be some misconfiguration on Jellyfin's side that Nginx fixes by having some other Defaults that Zoraxy doesn't have.

**Comment by Morethanevil** [comment]
The app on TV is broken, as mentioned in the last issue. It is fixed by users with those additional headers

I am using Jellyfin myself without problems similar to your setup 😃

**Comment by AzAel76** [comment]
To be clear. I imported my wildcard cert from npm, it was not working for me because I didn't import the full chain certificate. Once I did my issue connecting with the ATV client was resolved. Hadn't had the time to look further into the websocket issue but did source it to the background link between jellyseer and jellyfin.

**Comment by tobychui** [comment]
Closing this due to inactive and seems solution has been proposed.
