### ISSUE TITLE
[HELP] Generate wildcard certificate with Cloudflare challenge

### ISSUE THREAD

**Issue by l0u1sg** [tobychui/zoraxy#215]
**What happened?**
Hello, I am new to this proxy and I am trying to generate a wildcard certificate for my domain using the Cloudflare challenge. Cloudflare is only used for DNS, nothing goes through their proxy. I am a bit lost because it is asking for several keys and I don't necessarily know where to look... Could someone help me and tell me where to find these keys or send me documentation?

**Describe what have you tried**
I have already tried generating API keys that allow access to the zones, I found my zone ID, but I think it is the AuthKey and AuthToken fields that I cannot find.

**Describe the networking setup you are using**
Here are some example, commonly asked questions from our maintainers: 
- Are you using the docker build of Zoraxy? yes
- Your Zoraxy version? 3.0.7
- Are you using Cloudflare? only for DNS, not for proxy
- Are your system hosted under a NAT router? No

![CleanShot 2024-06-23 at 16 45 55@2x](https://github.com/tobychui/zoraxy/assets/46707587/82eb1fdb-6baf-48b9-aa68-76ab11d6280c)

**Comment by yeungalan** [comment]
![image](https://github.com/tobychui/zoraxy/assets/12872405/aee11e80-528b-424d-a4e3-c35c774268c3)

You may get the Auth Token here

WL:
https://dash.cloudflare.com/profile/api-tokens

**Comment by AlliAlliAlli** [comment]
I hate to say it but I'm also confused on the wording here. So the second link you posted lists 4 different env variables. Am I right to assume Zoraxy's variables go in the same order as the ones listed in that link?

AuthEmail = CF_API_EMAIL
AuthKey = CF_API_KEY  (aka Global API Key)
AuthToken = CF_DNS_API_TOKEN
ZoneToken = CF_ZONE_API_TOKEN

Is this correct?

**Comment by yeungalan** [comment]
Yes that's right, @tobychui will you fix the naming issue?

**Comment by AlliAlliAlli** [comment]
Thanks for confirming, I just wanted to make sure. :)

**Comment by tobychui** [comment]
> Yes that's right, @tobychui will you fix the naming issue?

Maybe. That is the key used by lego and mapping them in Zoraxy to be used once during certificate setup seems involving too much work. Maybe we can fix that after the localization project is ready and treat it as a kind of translation / text rewrite.

**Comment by AzAel76** [comment]
Maybe add it to the documentation in the interim. I had similar experiences but figured it out then ran into further issues due to using cnames pointing to a dynamic DNS service instead of A records. CloudFlare would fail to update the DNS challenge on my domain because it was trying to use or being sent my dynamic DNS domain.

**Comment by l0u1sg** [comment]
It worked for me, thanks @yeungalan

**Comment by yeungalan** [comment]
Glad it worked :)

**Comment by tobychui** [comment]
As this seems working, I am closing this help issue.
For future visitors, **you do not need to fill in all 4 fields** for Cloudflare DNS challenge. You only need to fill in the email (AuthEmail) and the global API token (AuthKey) and it will just works.
