### ISSUE TITLE
Duckdns does not get a cert

### ISSUE THREAD

**Issue by ChristoffBo** [tobychui/zoraxy#217]
Duckdns cant get a cert. Tried wild card and without.

Either times out or moans about some kind of auth failure.
Refused for acme client

Npm works fine.

**Comment by tobychui** [comment]
`Duckdns cant get a cert` is not enough information for debugging and the help template is here for a reason.
Check your authentication credentials, network setups or keep using NPM.

**Comment by ChristoffBo** [comment]
Ok will stick to a proxy that acttually works.

**Comment by tobychui** [comment]
> Ok will stick to a proxy that acttually works.

I will lock and keep this issue as this is a really typical example on how a not-helpful request and feedback looks like.
For future visitors, if you are trying to report an issue or ask for help, please remember to include these information.

- What have you done
- What else you have tried to debug it
- Include relevant information (e.g. screenshot, network traces or anything that might be helpful for the devs to figure out the issues).

The concept of open source is not that you can get software and support for free, but rather a platform that allow people to contribute together and make something better and more useful for everyone. Take a look at [this post](https://github.com/tobychui/zoraxy/discussions/154) for more information.
