### ISSUE TITLE
[BUG] Control Access (Whitelist) not working properly

### ISSUE THREAD

**Issue by elBelgg** [tobychui/zoraxy#223]
**Describe the bug**
If I activate Access Control to only allow Spain and try to connect with a Spanish IP, it won't let me connect.

**To Reproduce**
1. Go to 'Access Control'
2. Click on 'Whitelist'
3. Add 'Spain' to the whitelist
4. Enable whitelist
5. Connect to the domain with a Spanish IP
6. See error "403 - Forbidden"

**Expected behavior**
It should allow me to see the web instead of the blocking page

**Additional context**
If I try to connect with the mobile data instead with the IP of the router it allows me to see the website. Also, if I try allowing my own IP, it doesnt works.

**Comment by tobychui** [comment]
@elBelgg The GeoIP country code resolver might not be 100% accurate. It only holds correct for around 80 - 90% of the time as IP range for each countries are changing daily.  In your case, I would suggest using IP whitelist instead if you know your home / workplaces public ip address.

**Comment by elBelgg** [comment]
Yes, I tried but it doesn't work, I don't know why.

**Comment by tobychui** [comment]
@elBelgg I don't know why it didn't work on your network as well. 

Every homelab have different networking environments and setups. I am not a magician that knows all about your setup and how your requests are routed. But from what I saw, GeoIP whitelist and blacklist did works (at least in countries that I can tests with).

**Comment by elBelgg** [comment]
Okey, I will try tomorrow then

**Comment by elBelgg** [comment]
Whitelisting the router's IP makes it work correctly.

**Comment by tobychui** [comment]
Are you connecting to your reverse proxy using your own public IP address when you are within your house? Otherwise that feels weird 🤔

**Comment by elBelgg** [comment]
Yes, that is. You can close it
