### ISSUE TITLE
[ENHANCEMENTS] - Add the ability to download certificates that have been issued from the Administration interface

### ISSUE THREAD

**Issue by AX-AMote** [tobychui/zoraxy#227]
**Describe the solution you'd like**
Add the ability to download certificates that have been issued from the Administration interface.

**Describe alternatives you've considered**
I would navigate the files manually and download using SFTP.

**Additional context**
Not that this is meant to be a copy of the current functionality in NPM, but this feature is available there.

**Comment by tobychui** [comment]
@AX-AMote Yeah sure, will do 👍🏻

**Comment by tobychui** [comment]
![圖片](https://github.com/user-attachments/assets/36bd726c-1856-4788-bbac-4d2a996aa705)

In the next release you can download the cert by clicking on the cert domain key in the list under TLS tab.
