### ISSUE TITLE
[BUG] dns provider - Netcup propagation timeout

### ISSUE THREAD

**Issue by dschense** [tobychui/zoraxy#231]
**Describe the bug**
While getting Cert from Netcup with DNS-Challenge, I get a propagation timeout every time.

> Error: one or more domains had a problem: [*.example.com] propagation: time limit exceeded: last error: NS second-dns.netcup.net. returned SERVFAIL for _acme-challenge.example.com.

Other providers are working fine.

**To Reproduce**
create cert for sub or wildcard.
using credentials:
```
NETCUP_API_KEY
NETCUP_API_PASSWORD
NETCUP_CUSTOMER_NUMBER
```

Netcup.de is very slow in propagating the DNS changes. I can see the TXT is properly written over the API.
There are some more custom API configurations to use.

https://go-acme.github.io/lego/dns/netcup/

```
NETCUP_HTTP_TIMEOUT	API request timeout
NETCUP_POLLING_INTERVAL	Time between DNS propagation check
NETCUP_PROPAGATION_TIMEOUT	Maximum waiting time for DNS propagation
NETCUP_TTL	The TTL of the TXT record used for the DNS challenge
```

maybe adding a custom field to cert creation for using custom api configurations?

**Comment by tobychui** [comment]
@dschense Yes, but as Zoraxy is design to be automating as much config as possible, I would prefer to add an exception rule on this DNS provider instead. 

Maybe you can provide me the best interval and timeout value according to your experience and let me code that into the next release instead?

**Comment by dschense** [comment]
@tobychui thats a good solution.
the provider does not clearly tell the correct time.
Most sources are talking about 900s, but some are going higher to 1200s.

maybe its best to take the 1200s for the timeout?

**Comment by nicedevil007** [comment]
@dschense 

are you able to get any netcup cert with dns challenge and zoraxy?
I installed zoraxy this morning and I'm always getting the propagation timeout.
Zoraxy itself is able to receive certs over LetsEncrypt. I tried it without the DNS challenge and this worked.

**Comment by dschense** [comment]
Yes, for me its working atm.
Changed the zoraxy DNS to Cloudflare.
Have to take a Look when iam at Home again.

**Comment by nicedevil007** [comment]
i stopped the time now and it seems to be much lower than the 1200s you wrote above :(

EDIT: Ok I checked the file that was updatet on your Issue post last year. This file is different structured now and the setting isn't there anymore.

I create a new Issue with referencing to this here.
