### ISSUE TITLE
[BUG] Renewal of wildcard cert

### ISSUE THREAD

**Issue by chatainsim** [tobychui/zoraxy#249]
**Describe the bug**
Trying to renew a wildcard certificat.

**To Reproduce**
1. Go to TLS / SSL Certificates
2. Click on arrow to renew a woldcard certificat
![image](https://github.com/user-attachments/assets/7fd7f7b9-1c1f-467f-b90b-b262024cb87b)

4. Error happen
```
 Acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Invalid identifiers requested :: Cannot issue for "_.xxxxxx.fr": Domain name contains an invalid character
```
![image](https://github.com/user-attachments/assets/dd150abf-7d13-4e69-8142-fb4479c5af4a)

**Expected behavior**
Renewal of wildcard certificat

**Host Environment (please complete the following information):**
-  Arch: amd64
 - Device: LXC container on Proxmox host
 - OS: Debian
 - Version 12 Bookworm

**Additional context**
I've created the wildcard using *.xxxxx.fr and * got change to _
Using DNS challenge with Infomaniak
Same thing happen with DNS challenge with OVH

Is there some logs files for ACME cert error ?

**Comment by tobychui** [comment]
This seems like just a front-end problem. Can you try to replace the `renewCertificate` function using developer tool in `cert.html`?

```javascript
function renewCertificate(domain, dns, btn=undefined){
        let defaultCA = $("#defaultCA").dropdown("get value");
        if (defaultCA.trim() == ""){
            defaultCA = "Let's Encrypt";
        }
        //Get a new cert using ACME
        msgbox("Requesting certificate via " + defaultCA  +"...");

        //Request ACME for certificate
        if (btn != undefined){
            $(btn).addClass('disabled');
            $(btn).html(`<i class="ui loading spinner icon"></i>`);
        }
        
        //New fixes for _ replacement
        if (domain.includes("_.")){
            domain = domain.replace("_.","*.");
        }

        obtainCertificate(domain, dns, defaultCA.trim(), function(succ){
            if (btn != undefined){
                $(btn).removeClass('disabled');
                if (succ){
                    $(btn).html(`<i class="ui green check icon"></i>`);
                }else{
                    $(btn).html(`<i class="ui red times icon"></i>`);
                }
                
                setTimeout(function(){
                    initManagedDomainCertificateList();
                }, 3000);
            }
        });
    }

```

This should replace the `_.` in the filename to `*.` before passing into the obtainCertificate function (which I just use it as a black box)

**Comment by chatainsim** [comment]
I haven't found this function but I've changed this:
![image](https://github.com/user-attachments/assets/296b07a5-996a-400b-8527-2568b4c73512)
to:
![image](https://github.com/user-attachments/assets/f210b58b-65b2-4e99-8dd6-755c9a772f46)
and it worked !

**Comment by chatainsim** [comment]
Tested with another wildcard for another domain and it worked too.

**Comment by chatainsim** [comment]
Thank you @tobychui
And thanks for this great project :1st_place_medal:
