### ISSUE TITLE
[ENHANCEMENTS] Exception for Subfolders

### ISSUE THREAD

**Issue by ExXxtr3me** [tobychui/zoraxy#25]
**Is your feature request related to a problem? Please describe.**
I would like to use basic authentication for some of my dockers like Sonarr and Radarr, but i need the subfolder /api to be open. 

**Describe the solution you'd like**
An option to disable basic authentication for subfolders

**Comment by tobychui** [comment]
Just a quick question for @ExXxtr3me, do you think a wildcard options will be suitable for your use case? 
Or for newbies, a proper UI with checkbox and add buttons that allow adding multiple sub-folders will be a better design option?

**Comment by ExXxtr3me** [comment]
> Just a quick question for @ExXxtr3me, do you think a wildcard options will be suitable for your use case? Or for newbies, a proper UI with checkbox and add buttons that allow adding multiple sub-folders will be a better design option?

A check box where we could specify a subfolder would be nice but i would take what i can get. :)

**Comment by tobychui** [comment]
Feature added in v2.6.6. You can find it under Edit Proxy Endpoint > Basic Auth [Edit Settings] > Authentication Exclusion Paths
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/efe6e20d-9479-43bb-9073-60fbf64d396a)

**Comment by ExXxtr3me** [comment]
Awesome, will test it as soon as the docker gets updated. 👍

**Comment by tomcatcw1980** [comment]
Hi there, 

great project, many thanks for your work tobychui.

I just want it the other way around. How should I set it up if I want to allow everything, but a basic auth query should appear for a certain subfolder? Ex: 

https://sub.foo.bar/* should be allowed, but
https://sub.foo.bar/admin the query should come up

Would be nice if you have an idea.

Many thanks and best regards
