### ISSUE TITLE
[HELP] Setup Proxy Rules for Peertube

### ISSUE THREAD

**Issue by chatainsim** [tobychui/zoraxy#252]
Hello,
I'm trying to configure a proxy rules for Peertube.

Here is the nginx config file: https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube

But how can I add @api_websocket or location ~ ^/api/v1/(videos|video-playlists|video-channels|users/me) for exemple ?

I've tried this but it's seems to not working as it add a / before @api:
![image](https://github.com/user-attachments/assets/eb99666f-a528-4d8b-a18c-083e2f337dab)

Thank you.

**Comment by tobychui** [comment]
I am not sure what you are trying to do here. Have you tried remove all virtual directory config and just let Zoraxy deal with the connection automatically?

**Comment by chatainsim** [comment]
Upload is failing but I will try and tell you if it's still failing 
Thanks

**Comment by chatainsim** [comment]
Woh it's magical 😉
It's working fine without virtual directory.
Thank you.
Sorry, I'm new to Zoraxy.
