### ISSUE TITLE
[ENHANCEMENTS] ppc64el support

### ISSUE THREAD

**Issue by krosseyed** [tobychui/zoraxy#262]
**Is your feature request related to a problem? Please describe.**
This is a feature request

**Describe the solution you'd like**
A build to run on ppc64el

**Describe alternatives you've considered**
I have been running this on ARM, but it would be useful to be able to have this running on all of my weird platforms.

**Additional context**
I can build for ppc64el if there is a guide on how to do this? I didn't find a build from source guide.

**Comment by tobychui** [comment]
@krosseyed it is called "cross compilation" and you can clone the source code, download the go compiler and build the project yourself targeting the ppc64le platform.

```
git clone https://github.com/tobychui/zoraxy
cd ./zoraxy/src/
go mod tidy

export GOARCH=ppc64le
export GOOS=linux
go build -o zoraxy
```

if you are using Windows
```
set GOARCH=ppc64le
set GOOS=linux
go build -o zoraxy
```

Note that this project do not officially support PowerPC, use it at your own risk

**Comment by krosseyed** [comment]
@tobychui Thanks for sending that information over, and now after reading the README.md I noticed that there was a section for building from source. I should have tried that first, and thankfully I dont have to cross compile as I have the real hardware to do this on.

I will report back after doing the build, but I will close this ticket for now as in theory, there is enough info to build on any platform.
