### ISSUE TITLE
[BUG] 3.0.8 Config Updater didn't seem to work

### ISSUE THREAD

**Issue by KShivum** [tobychui/zoraxy#265]
**Describe the bug**
Updating from 3.0.2 to 3.0.9 all HTTP Proxies are gone

**To Reproduce**
1. Run 3.0.2 with Proxies
2. Docker pull and update compose file with latest
3. Run container

**Expected behavior**
HTTP Proxies should carry over to new version

**Host Environment (please complete the following information):**
-  Arch: x64
 - OS: Fedora (Host)
 - Version: 39
 - Docker Version: 3.0.9? 

**Additional context**
I'm not really upset since it is on me for not reading releases before pulling, but it seems like something happened for the updater to not update the proxy config. Although I'm not sure if it is because I had that version file

**Comment by tobychui** [comment]
Hi @KShivum,

It is a known issue as the updater is only introduced on 3.0.8, you will need the configs in v3.0.7 format before upgrading (aka skip versions upgrade is not supported on before v3.0.9). There are no automatic fixes right now other than manually upgrading the config to v3.0.8 format. But with the introduction of the auto upgrader and cross version support in v3.0.9, I am pretty sure there will be no similar issues like this in coming future.

See https://github.com/tobychui/zoraxy/issues/245 for more information on manual upgrade methods in docker and native env.

**Comment by KShivum** [comment]
Ah ok, makes sense. Luckily, I had a picture with all of my proxies for an unrelated issue
