### ISSUE TITLE
[ENHANCEMENTS] - Enable the ability to specify a certificate manually per service.

### ISSUE THREAD

**Issue by freedbygrace** [tobychui/zoraxy#266]
Right now, I have no idea how to make a wildcard certificate be the certificate used for a proxy entry.

The ACME integration should be smoother and more concise. Also, it should be configurable after the proxy entry has been created.

I really like this software! I am actually in process of migrating away from my current reverse proxy.

**Comment by tobychui** [comment]
Hi @freedbygrace 

Seems you are coming from nginx proxy manager. In Zoraxy, we do that automatically. You do not need to specify / assign a certificate manually to a hostname. As soon as you have a wildcard certificate in the certificate storage, Zoraxy will pick the suitable one for you based on the host name your downstream clients are requesting. 

Just go to the ACME snippet, generate a wildcard certificate using DNS challenge and after it is done and show up in the list, it is ready to use (will automatically assign to proxy rules that matches the wildcard)

**Comment by freedbygrace** [comment]
Hey thanks!

I still think this is a issue because I am testing right now with a wildcard certificate that has been successfully issued.

I have now configured split horizon DNS yet, so I am testing with a mobile hotspot to have proper external connection flow.

```
I get "this site cannot provide a secure connection."

The connection for this site is not secure
zoraxy.gracesolution.info sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

This site does not have a certificate.

Because this connection is not secure, information (such as passwords or credit cards) will not be securely sent to this site and may be intercepted or seen by others.
```
So the site is not mapping the certificate properly. 
I do understand the automatic mapping, but I think it should be a toggle? 
This would allow for more concise experience. Right now, I have no idea if the matching is working. 
Also the wildcard certificate has a "_.mydomain.com" and not "*.mydomain.com".
 I read elsewhere in the issues that you are aware of this, so I am not double reporting.
