### ISSUE TITLE
[BUG] Problem generating wilcard certificates with gandi

### ISSUE THREAD

**Issue by dextouu** [tobychui/zoraxy#273]
**Describe the bug:**

Problem generating wilcard certificates with Gandi dns .

1.  Go to TLS / SSL Certificates
2.  Click on arrow on ACME Auto-Renewer to generate a wildcard certificate with DNS verification.
3.   Error on generate .
  ` Error: one or more domains had a problem: [xxxxx.xyz] [xxxx.xyz] acme: error presenting token: unable to get TXT records for domain selfhosted-amorosa.xyz and name _acme-challenge: unable to communicate with the API server: error: Get "xxxxx.xyz/domains/xxxxx.xyz/records/_acme-challenge/TXT": unsupported protocol scheme "   `

![ssl](https://github.com/user-attachments/assets/30e67250-a7a2-4503-ad36-fc43c9f9863c)

**Expected behavior**

Generated a wildcard certificate

Host Environment (please complete the following information):

Arch: amd64
Device: LXC container on Proxmox host
OS: Debian
Version 12 Bookworm

Additional context
Certificate generation with the "Lego" cli software works and the certificate is generated.
I don't know where the problem comes from, I put the same information on Zoraxy and the "Lego" software

**Comment by yeungalan** [comment]
taking a look

**Comment by yeungalan** [comment]
```
2024/07/31 00:37:40 [INFO] CA not set. Using default
2024/07/31 00:37:40 [ACME] Obtaining certificate...
2024/07/31 00:37:40 [INFO] Using https://acme-v02.api.letsencrypt.org/directory for CA Directory URL
2024/07/31 00:37:40 [INFO] acme: Registering account for xxxxxxx@gmail.com
2024/07/31 00:37:41 [INFO] [r5desktop.alanyeung.co] acme: Obtaining bundled SAN certificate
2024/07/31 00:37:41 [INFO] [r5desktop.alanyeung.co] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/384155413017
2024/07/31 00:37:41 [INFO] [r5desktop.alanyeung.co] acme: Could not find solver for: tls-alpn-01
2024/07/31 00:37:41 [INFO] [r5desktop.alanyeung.co] acme: Could not find solver for: http-01
2024/07/31 00:37:41 [INFO] [r5desktop.alanyeung.co] acme: use dns-01 solver
2024/07/31 00:37:41 [INFO] [r5desktop.alanyeung.co] acme: Preparing to solve DNS-01
2024/07/31 00:37:41 [INFO] [r5desktop.alanyeung.co] acme: Cleaning DNS-01 challenge
2024/07/31 00:37:41 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/384155413017
2024/07/31 00:37:41 error: one or more domains had a problem:
[r5desktop.alanyeung.co] [r5desktop.alanyeung.co] acme: error presenting token: gandi: unable to communicate with the API server: error: Post "hkwtc.org": unsupported protocol scheme ""
```

Able to recreate the issue, checking baseURL configuration

**Comment by dextouu** [comment]
Hi, I just noticed my mistake, I must be reading poorly or be tired. It was necessary to add the following URL: https://api.gandi.net/v5/livedns.
I tested it works with adding the missing url as a base, thank you .

on the other hand, I can say it is the only software that is successful with a UI and complete, compared to caddy or traefik, without a graphical interface

**Comment by tobychui** [comment]
@dextouu Oh, as suggested by @yeungalan base on your bug report, we have removed the baseURL field from the v3.1.0 release. Can you double check if that also works for you after upgrading Zoraxy?

**Comment by dextouu** [comment]
hello, once the update is done, it works.

**Comment by tobychui** [comment]
Cool, I am closing this as fixed.
