### ISSUE TITLE
[BUG] Path Traversal Vulnerability with Static Web Server

### ISSUE THREAD

**Issue by YamiOdymel** [tobychui/zoraxy#274]
**Describe the bug**

A **logged in** User can access `/etc/passwd` with Web Directory Manager in Static Web Server

**To Reproduce**
1. Go to the `Static Web Server` tab.
2. Click on `index.html` in the `Web Directory Manager` section.
3. The URL `http://localhost:8000/api/fs/download?file=/index.html&preview=true` appeared.
4. Replace it with `http://localhost:8000/api/fs/download?file=/../../../../../../../../../../../etc/passwd&preview=true`.

**Expected behavior**

It should return `file not found` because it is out of bounds.

**Screenshots**

![image](https://github.com/user-attachments/assets/0eb6f281-fa2c-4ff6-9ca9-d5f151276cae)

**Host Environment (please complete the following information):**
- Arch: amd64
- OS: Ubuntu 22.04 (WSL v2)
- Zoraxy Version: v3.0.9

**Additional context**

Steps provided in [Golang Path Traversal Guide: Examples and Prevention](https://www.stackhawk.com/blog/golang-path-traversal-guide-examples-and-prevention/)

- Reflect the relative paths to the actual system path with [`filepath.Clean()`](https://pkg.go.dev/path/filepath#Clean).
- Evaluate the symlinks to ensure that files within bounds are not pointing outside of the bound using [`filepath.EvalSymlinks()`](https://pkg.go.dev/path/filepath#EvalSymlinks).
- Make sure the final path is within a trusted root using [`filepath.Dir()`](https://pkg.go.dev/path/filepath#Dir).

**Comment by krosseyed** [comment]
This also affects ARM64 on v3.1.0. I am able to reproduce this on my setup.

**Comment by tobychui** [comment]
@krosseyed No worry, this API require authentication before access and this do not pose an immediate security vulnerability to Zoraxy. This will be fixed in the next release.

**Comment by krosseyed** [comment]
Ah, I see access is denied to that URL after logging out. I do have to log in to get traversal to /etc/passwd, and I do not expose Zoraxy directly to the internet.

Thanks for being proactive on this @tobychui and I really enjoy using this software!

**Comment by klisza1993** [comment]
For the future maybe it would be better to not post it publicly? :D

**Comment by YamiOdymel** [comment]
> For the future maybe it would be better to not post it publicly? :D

I did feel sorry and private messaged @ tobychui to talk about this 💀💀

I'll be more careful next time to avoid any concerns

**Comment by tobychui** [comment]
Patched
