### ISSUE TITLE
[BUG] zoraxy do not start without ipv6 

### ISSUE THREAD

**Issue by fdefilippo** [tobychui/zoraxy#276]
./zoraxy_linux_amd64 -port=192.168.1.10:6000
Checking required config update
[2024-07-31 17:10:42.184312] [auth] [system:info] Authentication session key loaded from database
[2024-07-31 17:10:42.582005] [static-webserv] [system:info] Static Web Server started. Listeing on :5487
2024/07/31 17:10:42 [zeroconf] no suitable IPv6 interface: listen udp6 [ff02::]:5353: socket: address family not supported by protocol
2024/07/31 17:10:42 Environment variable ZT_AUTH not defined. Trying to load authtoken from file.
2024/07/31 17:10:42 Failed to initialize resolver: listen udp6 [ff02::]:5353: socket: address family not supported by protocol

**Comment by tobychui** [comment]
@fdefilippo That was from the mdns scanner. As your bug report is not complete (please follow the template next time), I think you are running zoraxy in a mdns not supported environment. You can disable the mdns scanner via `-mdns=false`.
