### ISSUE TITLE
[Misinformation] Wrong Country name.

### ISSUE THREAD

**Issue by techlabgr** [tobychui/zoraxy#287]
Hi my friend how are you.?
First of all congratulation for your very nice work with Zoraxy.
I write you because you make a mistake with the name of a country .............. there is NO country name Macedonia, Macedonia is a BIG ANCIENT territory and NOT a country. The only country that use this name is "Republic of North Macedonia" and NOT ONLY "Macedonia".

Please consider inform your self with the below article.
https://en.wikipedia.org/wiki/North_Macedonia

_"The country became a member of the [United Nations](https://en.wikipedia.org/wiki/United_Nations) (UN) in 1993, but as a result of a [dispute with Greece](https://en.wikipedia.org/wiki/Macedonia_naming_dispute) over the [name "Macedonia"](https://en.wikipedia.org/wiki/Macedonia_(terminology)), it was admitted under the provisional description "the former Yugoslav Republic of Macedonia" (abbreviated as "FYR Macedonia" or "FYROM"). In 2018, the dispute was [resolved with an agreement](https://en.wikipedia.org/wiki/Prespa_Agreement) that the country should rename itself "Republic of North Macedonia". **This renaming came into effect in early 2019**."_

Please correct the mistake because by writing ONLY name "Macedonia" you insult ALL the Greek people.

Thanks in advance.
Kostas K.

**Comment by tobychui** [comment]
Hi @techlabgr ,

Thanks for the feedback. The country selector dropdown is provided by the front-end css framework we are using called "Semantic UI". You can see in the screenshot below, this country name is provided in their example. 

![圖片](https://github.com/user-attachments/assets/73793ccd-4229-4fbc-a0b0-5dbf50fd14ce)

I think I can override it in Zoraxy temporarily, but it would be better for you to create a PR of the upstream framework so this can get a "proper" fix in future releases and projects that uses this framework.

**Comment by techlabgr** [comment]
Hi Toby

Thank you very much for your reply, can you please tell me how i can create
a PR of the upstream framework.?

**Comment by tobychui** [comment]
@techlabgr Here is the repo for Semantic UI
https://github.com/Semantic-Org/Semantic-UI

**Comment by techlabgr** [comment]
Thanks very much Toby i will make donation for your project.
My name is Kostas Kakaslakoudis and you are welcome to Greece any time.

Thanks in advance.
