### ISSUE TITLE
[BUG] upstream timeout - context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by magicgg91** [tobychui/zoraxy#291]
Hello, I replaced NPM with Zoraxy and it works well !
The only error I got is with 1 upstream service which is randomly unavailable during 2-5 minutes.
I see in logs following error.
This is a Ghost blog running in a Docker container, and I already updated it to last version 5.90.
All my other services doesn't experience any issue.

`[2024-08-27 11:22:07.389904] [uptime-monitor] [system:error] Ping upstream timeout. Assume offline: Get "https://192.168.10.101:2368": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Host Environment**
-  Arch: arm64
 - Device: Ubiquiti UDM SE with nspawn container
 - OS: Debian 12

**Comment by magicgg91** [comment]
My investigations are pushing me to say it's not a zoraxy issue.
I think it's due to the fact zoraxy is on a separate network as NPM was, and I've no IPS/IDS on it, causing zoraxy to be banned for 5 minutes when an attack is detected.
I've added zoraxy as trusted, and observing.

**Comment by tobychui** [comment]
It seems like it is what the error log saids, the uptime monitor cannot reach one of your upstream. 

The uptime monitor will ping your upstream every few minutes so yes, it might get mistakenly assume the request is attack or bot by your upstream.  If you have access to the bot filter in your upstream, you can whitelist `zoraxy-uptime/1.1` user agent (zoraxy uptime monitor bot).

**Comment by tobychui** [comment]
Closing this as it seems solved and no update is provided.
