### ISSUE TITLE
[HELP] Failed to build from source 

### ISSUE THREAD

**Issue by GamingForLive** [tobychui/zoraxy#293]
**What happened?**
When trying to build the latest commit i get a bunch of errors that are going past my knowledge

**Describe what have you tried**
ive tried to fully delete the zoraxy directory and do a fresh git clone

**Describe the networking setup you are using**
[deemed irellevant in this case by me]

**Additional context**
Here are the errors i get when running ```go build``` (`go tidy` appears to run fine)
now based of the erros id say that go is probabally having some issue or i potentially did something wrong as this was my first time installing go but i did my best to follow the instructions to the letter and unfortunately dont know enough about go to troubbleshoot this)

```
# runtime
/usr/local/go/src/runtime/mbitmap_noallocheaders.go:53:2: mallocHeaderSize redeclared in this block
        /usr/local/go/src/runtime/mbitmap.go:71:2: other declaration of mallocHeaderSize
/usr/local/go/src/runtime/mbitmap_noallocheaders.go:54:2: minSizeForMallocHeader redeclared in this block
        /usr/local/go/src/runtime/mbitmap.go:101:2: other declaration of minSizeForMallocHeader
/usr/local/go/src/runtime/mbitmap_noallocheaders.go:60:6: heapBitsInSpan redeclared in this block
        /usr/local/go/src/runtime/mbitmap.go:112:6: other declaration of heapBitsInSpan
/usr/local/go/src/runtime/mbitmap_noallocheaders.go:243:6: bulkBarrierPreWrite redeclared in this block
        /usr/local/go/src/runtime/mbitmap.go:418:6: other declaration of bulkBarrierPreWrite
/usr/local/go/src/runtime/mbitmap_noallocheaders.go:316:6: bulkBarrierPreWriteSrcOnly redeclared in this block
        /usr/local/go/src/runtime/mbitmap.go:504:6: other declaration of bulkBarrierPreWriteSrcOnly
/usr/local/go/src/runtime/mbitmap_noallocheaders.go:695:6: heapSetType redeclared in this block
        /usr/local/go/src/runtime/mbitmap.go:705:6: other declaration of heapSetType
/usr/local/go/src/runtime/mbitmap_noallocheaders.go:704:6: getgcmask redeclared in this block
        /usr/local/go/src/runtime/mbitmap.go:1750:6: other declaration of getgcmask
/usr/local/go/src/runtime/mbitmap_noallocheaders.go:798:6: userArenaHeapBitsSetType redeclared in this block
        /usr/local/go/src/runtime/arena.go:553:6: other declaration of userArenaHeapBitsSetType
/usr/local/go/src/runtime/mbitmap_noallocheaders.go:891:6: typePointers redeclared in this block
        /usr/local/go/src/runtime/mbitmap.go:122:6: other declaration of typePointers
/usr/local/go/src/runtime/mbitmap_noallocheaders.go:936:6: heapBitsSlice redeclared in this block
        /usr/local/go/src/runtime/mbitmap.go:587:6: other declaration of heapBitsSlice
/usr/local/go/src/runtime/mbitmap_noallocheaders.go:936:6: too many errors
```

**Comment by GamingForLive** [comment]
[Please disregard worked arround by using a pre compiled version]

**Comment by tobychui** [comment]
Hi @GamingForLive 

This is not a Zoraxy issue. Seems you have screwed up your Go compiler installation. Try reinstall go compiler and build again.

**Comment by GamingForLive** [comment]
Hi,
first of all thanks for the fast reply

Yea i thought so but like i said ive decided to go with a pre compiled download and that has fixxed my issue.
I dont really care about building from source. Althought after looking at the link provided by you it looks like all i was missing was to build the go directorry so i might try it again tomorrow

**Comment by tobychui** [comment]
Closing this issue as this is not directly related to this project and there are no further updates.
