### ISSUE TITLE
[ENHANCEMENTS] Graph improvements

### ISSUE THREAD

**Issue by PassiveLemon** [tobychui/zoraxy#294]
**Is your feature request related to a problem? Please describe.**
- The time interval is displayed as Unix time. I can't read Unix time at a quick glance so it can be difficult to determine timestamps. A setting to enable conversion to local time would be nice.
- The timestamp network in/out stats appear to be in bits, some conversion for this would also be nice.
- Viewing in intervals such as last minute, hour, day, week, custom, etc.

**Additional context**
![image](https://github.com/user-attachments/assets/bc5353f2-5dbf-49c8-bd74-4729bf7e6055)

**Comment by tobychui** [comment]
![圖片](https://github.com/user-attachments/assets/936c0326-d1f4-4a7f-9654-0305b211fc43)

I just realized I missed this enhancement request. This will be updated to local timezone date-time value in the next release.
