### ISSUE TITLE
[ENHANCEMENTS] Default to reading from file if empty string is passed in `-ztauth`

### ISSUE THREAD

**Issue by PassiveLemon** [tobychui/zoraxy#296]
**Is your feature request related to a problem? Please describe.**
In https://github.com/tobychui/zoraxy/pull/295, I have to test if ZTAUTH is set before I can add it as a flag when running Zoraxy. If I pass an empty string it thinks im providing it `''` as the key, which obviously does not work.

**Describe the solution you'd like**
When an empty string is passed in `-ztauth`, default to reading from authtoken.secret so the test is not required. This simplifies the entrypoint script a little bit.

**Comment by tobychui** [comment]
Hey @PassiveLemon ,

The current code base already implement such feature for empty string check.  See the following file for implementation detail.

https://github.com/tobychui/zoraxy/blob/563a12c860474cee7151a7f904ca29763ca911e7/src/start.go#L231

If you are having issue with empty string, I guess it might the issue regarding the environment, permission (if Zoraxy can read the secret file or not) or issue regarding connections between the zerotierd API server. Let me know if you need further information 👍🏻

**Comment by PassiveLemon** [comment]
Ah, it must be because I was passing in `"''"` and not just `''`
