### ISSUE TITLE
Add custom timeout for ACME DNS validation

### ISSUE THREAD

**Issue by jwgn** [tobychui/zoraxy#300]
**Is your feature request related to a problem? Please describe.**
ACME DNS validation with deSEC failed multiple times. It seems the timeout is too tight.
In Proxmox, I faced the same problem, adding a 30 second additional timeout in the GUI solved it.

**Describe the solution you'd like**
Please add a customizable timeout option to the GUI.

**Describe alternatives you've considered**
None.

**Additional context**
This is related to discussion https://github.com/tobychui/zoraxy/discussions/268

**Comment by jwgn** [comment]
`Error: one or more domains had a problem: [<domain>.de] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.<domain>.de - check that a DNS record exists for this domain`

Happens over and over again. TXT record is correctly created and deleted afterwards. Have to request the certificate a dozen times until it works. Please increase the timeout or make it customizable.

**Comment by tobychui** [comment]
Hey @jwgn,

What DNS service provider you are using? Have you tried HTTP challenge as a work around for now?
I have just graduated last month and I am in the progress of moving to another city for my first job. I probably don't have time to fix anything in recent time, so if you need it urgently, please create a PR with the feature you want and I will try my best to review it  asap. Thanks!

**Comment by jwgn** [comment]
I am using deSEC, as stated in the initial message. HTTP challenge works.

**Comment by jwgn** [comment]
Solution is here: https://github.com/tobychui/zoraxy/discussions/268#discussioncomment-11019859

```
[Service]
Environment="DESEC_POLLING_INTERVAL=15"
Environment="DESEC_PROPAGATION_TIMEOUT=900"
Environment="DESEC_TTL=3600"
```

**Comment by tobychui** [comment]
Feature added in v3.1.2
![圖片](https://github.com/user-attachments/assets/ef6d448b-fbc6-4f15-83f2-bc654fa02d3a)
