### ISSUE TITLE
[HELP] Any option in virtual directory like nginx location =/ {}

### ISSUE THREAD

**Issue by LostALice** [tobychui/zoraxy#302]
Want to know is there any option or settings can setup match case like nginx when path equal to / and rewrite the url to sth like /foo/bar.html

this is my nginx conf file
```
location =/ {
    proxy_pass $forward_scheme://$server:$port/share/index.html;
    add_header X-Served-By $http_host;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    
    proxy_redirect off;
  }
```

**Comment by tobychui** [comment]
@LostALice Seems you are tying to use the `share` folder as the root of this subdomain?
Have you tried pointing your subdomain to the share folder when creating the proxy rule?
e.g. create a new proxy rule from `share.yourdomain.com` to `192.168.0.100:8080/share`

**Comment by LostALice** [comment]
Thx a lot its work
