### ISSUE TITLE
DockerHub image not updated

### ISSUE THREAD

**Issue by elBelgg** [tobychui/zoraxy#303]
Latest version in DockerHub is 3.1.0 instead of 3.1.1

**Comment by PassiveLemon** [comment]
Yep we're working on it. An issue occurs with ZeroTier when building which causes the GitHub action to fail.

**Comment by PassiveLemon** [comment]
Oops didnt mean to close it

**Comment by elBelgg** [comment]
Aah okey, I didnt know. Good luck with it :)

**Comment by tobychui** [comment]
@PassiveLemon Maybe we could include the older zerotier version in the next release. Currently I have no clue on how to fix it (nor why the issue only happens with newer version of zerotier) 😥 .

**Comment by PassiveLemon** [comment]
Sure, I could just have it build a version that works
