### ISSUE TITLE
[ENHANCEMENTS] Range port for stream proxy

### ISSUE THREAD

**Issue by nynjardin** [tobychui/zoraxy#304]
Just an option to add range of port instead of just a port in Stream Proxy. It can up the QoL when some app ask for a range of 100 ports, for exemple.

Thanks :)

**Comment by tobychui** [comment]
@nynjardin Isn't that the job of your upstream router? Like you can port forward a range of porrts to a single port behind the NAT server (like your gateway router). 

In the current implementation, for each listening port, Zoraxy will spawn a go-routine for listening that port. I am a bit worry if a ranged port listener (e.g. 100 ports to 1 port) running in user space and go's overhead might use a tons of resources to reach the same performance of a $50 USD network router.

**Comment by nynjardin** [comment]
@tobychui I've checked 2 routeur at home, and both haven't the possibility to route range of port to an unique port. And the serveur will wait for a range of port, I'm not sure to understand how to doing that if my routeur only send packet from 1 port or I'm missing something?

**Comment by tobychui** [comment]
@nynjardin Interesting, I thought most routers have this feature supported. Even the cheapest consumer grade routers have this as well. It looks something like this.
![未命名](https://github.com/user-attachments/assets/296adc8d-badd-47f1-a6fb-3d7f419ee190)

If you are not connecting from external network, then I might be interested to know more about your use case so I can better propose a solution for future versions of Zoraxy.

**Comment by nynjardin** [comment]
The router with internet connection look like that when I want to add range of port.
![image](https://github.com/user-attachments/assets/cf31b090-3974-493e-b6e1-2f1248697f09)

I just connected another routeur to see and it look like to have this kind of configuration.
![image](https://github.com/user-attachments/assets/58436079-5d72-43fc-80a1-0165311b9d39)

I'll take time to look deeper about this one.

In my case, it's to host game servers. I have a physical server with Zoraxy and several VMs with game servers on them. Ideally, I'd like to send all the traffic to the Zoraxy machine and then have Zoraxy send the data to the appropriate VM, to avoid having 2 places to set up port forwarding.

**Comment by nynjardin** [comment]
Ok, I've just realized that I need all the ports in both directions, to internet and to every VM that needs them. So this solution isn't possible anyway, I'll need a port range systematically.

For the moment, I'm going to use the router solution to do everything, it'll be easier than using the router when there's a port range and using Zoraxy when there's only one, especially as all my VMs are on the same IP range as the host and therefore the router connected to the Internet.

Thanks for your help though @tobychui, I'll keep an eye out to see if you find a solution in the future, knowing that Zoraxy has many other interesting features that I really like the idea of having everything in one place :)
