### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by Lolozendev** [tobychui/zoraxy#306]
Before any futher explaination, if any devs read this, your tool is🔥 !

**What happened?**
I tried to make a redirection from a subdomain to an external website and endpoit, but I ended up with a cloudflare error 521.

I wanted to redirect : From github.mydomain.com To https://www.github.com/MyGithubPAge

**Describe what have you tried**
I tried to create a redirection from github.mydomain.com To https://www.github.com/Lolozendev/

I checked copy path
I also made the redirection permanent 301

**Describe the networking setup you are using**
I'm using cloudflare as a dns and ssl/tls certificate provider
I'm using Zoraxy 3.1.1 built on a proxmox over a lxc container

**Comment by FirefoxNL** [comment]
Are you using Cloudflare tunnel or something similar? When I enter the following redirect rule, it works like a charm.

![image](https://github.com/user-attachments/assets/6033642d-b106-45f1-be14-11a8bae5cb4c)

**Comment by Lolozendev** [comment]
Ok, I was just answering this post and the error changed to 526, apparently for some reason my certificate was not valid (I just created it a few days ago) , I created a new one and replaced it now it works, thank you !
