### ISSUE TITLE
[BUG] Certificate Auto Renew not working

### ISSUE THREAD

**Issue by KmdKeen** [tobychui/zoraxy#316]
**Describe the bug**
Since updating to 3.1.0 / 3.1.1. auto renew is not working. 

**Expected behavior**
I have a lot of certificates and need them to be auto-renewed. Some of them are expiring in 6 days and should be renewed, but even with disabling/re-enabling the autorenew nothing changes. 

Manually renewing works!

**Screenshots**
![grafik](https://github.com/user-attachments/assets/80647a58-8808-4946-8dbf-89890e138962)

**Host Environment (please complete the following information):**
-  Arch: [amd64]
 - Device: Proxmox
 - OS: Debian LXC
 - Version 12

**Comment by tobychui** [comment]
@KmdKeen Thanks for the report. I am having the same issue on some of my homelab nodes. I will look into it recently and will let you know if I found something.

**Comment by tobychui** [comment]
> The sort-function in the certificate-table is working for the certificate name, but not the other columns like "Last Updated" or "Expires At"

Right, when you mention about this, now I notice that table should not be sortable using "Last Update" or "Expires At" as by default this should be sorted by domain name alphabetically. I will remove the sorting function on these fields in next release.

**Comment by KmdKeen** [comment]
Hey @tobychui ,

sure this issue is closed? I again have certificates not getting auto-renewed:

![grafik](https://github.com/user-attachments/assets/2338b0d0-0744-4851-8685-e6cea7a581c8)

**Comment by tobychui** [comment]
@KmdKeen I think it shd be fixed. I asked @yeungalan (ACME module maintainer) to test it out for me and he say it is ok.
Maybe you can provide us the log during Zoraxy startup and 24 hours after startup and see if the auto renewer have some issue on your system? If everything is working, you shd be able to see the auto renewer debug log like this.

```
2024-11-14 06:41:31.673091] [internal] [system:info] Starting ACME handler
[2024-11-14 06:41:31.677091] [cert-renew] [system:info] ACME early renew set to 30 days and check interval set to 86400 seconds
```

**Comment by KmdKeen** [comment]
Think I found the issue:

```
[2024-11-13 17:07:26.017423] [ACME] [system:error] Obtain certificate failed: error: one or more domains had a problem:
[sub.domain.tld] [sub.domain.tld] acme: error presenting token: could not start HTTP server for challenge: listen tcp :31267: bind: address already in use
```

Did restarting the service without another message like this and now the auto-update is working again. Thanks for the help!
