### ISSUE TITLE
[HELP][HTTP PROXY] Got 404 when disable TLS on proxy target 

### ISSUE THREAD

**Issue by zoechou** [tobychui/zoraxy#317]
**What happened?**
As the proxy-server and target endpoint are in private subnets, 
I tried to create a proxy rule that route the traffic to http endpoint, but got 404 error.

Confirmed that the we can reach http://${target_domain}/.... on the proxy instances.
But we also support https protocol for testing.

**Describe what have you tried**
- Create virtual directory to point to plain HTTP endpoint.
- Testing the proxy, get error code 404.
- Update the virtual directory enable TLS on proxy-target.
- Testing the proxy, can route the traffic to target endpoint.

Using curl command to verify the connection between proxy instance and target endpoint,
both http and https return status code 200.

**Describe the networking setup you are using**
Here are some example, commonly asked questions from our maintainers: 
- Are you using the docker build of Zoraxy?  yes
- Your Zoraxy version? 3.1.1
- Are you using Cloudflare? no
- Are your system hosted under a NAT router? no
- DNS record (if any)
  - search-in-proxy-test.${domain}, point to the ELB of proxy instances

**Comment by tobychui** [comment]
@zoechou Are you sure your upstream accept HTTP connection? The "TLS" option for proxy target means the connection between Zoraxy and your upstream server uses TLS (and 443, if not defined in URL), but not expose this virtual directory / subdomain with TLS.

**Comment by zoechou** [comment]
Yes, I'm sure that our upstream can accept HTTP connection. 
Verified by executing curl command on the proxy instance.
But there's few information in logs, hard to debug the issue.

Will capture the tcpdump record to check the traffic and packet flow,
can update the case later.

**Comment by zoechou** [comment]
We reverted the proxy back to nginx, there's no issue with nginx.
Also I found there's higher cpu utilization when using zaraxy to perform the reverse-proxy,
might monitor the performance on test environment and check if we can re-enable zaraxy,
thanks
