### ISSUE TITLE
[BUG] HEADER not set

### ISSUE THREAD

**Issue by play113** [tobychui/zoraxy#318]
**Describe the bug**
REMOTE_USER header not set

**To Reproduce**
1. Setup a http proxy
2. Edit and set 'Require Basic Auth'
3. Edit Credentials and add a test user
4. Custom Headers and add
      key=REMOTE_USER value=$remote_user

**Host Environment (please complete the following information):**
zoraxydocker/zoraxy:latest

**Comment by play113** [comment]
Or is there already a suitable variable that I can use here?

**Comment by play113** [comment]
please set header REMOTE_USER and X-Remote-User automatically correlated
... THX

**Comment by tobychui** [comment]
@play113 

Yeah ok, what upstream are you working with here? 
I don't personally use X-Remote-User, but sending out the header to upstream should not be a problem.

**Comment by play113** [comment]
thanks for the quick response
I am currently using your cool proxy in version 3.1.1.r3 from https://hub.docker.com/r/zoraxydocker/zoraxy

**Comment by play113** [comment]
for example, i use it like this
zoraxy with auth (set auth header) --> radical (dav-server)

**Comment by tobychui** [comment]
![圖片](https://github.com/user-attachments/assets/e9abe173-b7cb-404f-9550-05457e9ee734)
In the next release, if you login via Zoraxy's basic auth, the header should be automatically added.

**Comment by play113** [comment]
THX for your work and fast response
