### ISSUE TITLE
[ENHANCEMENTS] A functional wiki and a how-to for beginners

### ISSUE THREAD

**Issue by thespyboss** [tobychui/zoraxy#32]
**Is your feature request related to a problem? Please describe.**
It isn't really a problem but for some like me, it probably is. 

**Describe the solution you'd like**
A functional wiki. I am new to networking systems like this and I want to use your system, but with no how-to for starting the system, it is incredibly hard to figure out. 

**Describe alternatives you've considered**
Researching how to use reverse proxy systems but everything is either Apache or NGINX and those don't really apply to this system. 

**Additional context**
I am fine with helping write a how-to for this system because it really is amazing, I just need someone to oversee or someone to instruct on how the system is used and how to set it up past `sudo ./zoraxy -port=:8000`.

**Comment by tobychui** [comment]
@thespyboss Glad that you like this project!
I can provide you 1 to 1 support for exchanging a quick start guide written by you :D 
Please contact me directly via email at imuslab@gmail.com, or if you use Telegram, please also provide your telegram id in the email so I can PM you.

**Comment by tobychui** [comment]
Here is the [Getting Started](https://github.com/tobychui/zoraxy/wiki/Getting-Started) guide. 
Closing this issue as no one picking this up and write the wiki page.
