### ISSUE TITLE
[HELP] Console on Proxmox using wildcard SSL reverse proxy through Zoraxy gives an 1006 error - session does not establish

### ISSUE THREAD

**Issue by AhzurdanGit** [tobychui/zoraxy#323]
**What happened?**
As described in the headline: When using Zoraxy for reverse proxy on an wildcard certificate I get an 1006 error in Proxmox when trying to establish a console session. That does not happen when directly connection through Proxmox IP or regular DNS name. I had the same issues in the past using NGINX but that was solved with some kind of setting in NGINX.
Not sure what I need to enable to get that sorted out as well.

- Are you using the docker build of Zoraxy? yes - setup runs on macvlan

- Your Zoraxy version? latest
- Are you using Cloudflare? only using a cloudflare wildcard cert

**Comment by jcastro** [comment]
I believe on nginx proxy manager the setting was to enable websockets

**Comment by AhzurdanGit** [comment]
yes. think you are right and this is how i got it working in NGINX. Isnt websockets automatically enabled in Zoraxy - thus does not work...

**Comment by tobychui** [comment]
@AhzurdanGit Websocket in zoraxy is automatically detected and enable if the request contains the correct "Upgrade" header. As I recall eventually we get it working in #106. Maybe you can ask for promox user's help in that discussion thread?

**Comment by jcastro** [comment]
I’m using zoraxy with proxmox and it’s working ok

**Comment by AhzurdanGit** [comment]
Ah

**Comment by AhzurdanGit** [comment]
Nevermind.. I was checking #106 and redoing all the settings and it automagically works :D Thanks guys for responding. So selecting all in upstream seemed to do the trick. I will retry with my other mini-pcs and report up if that is not working. Good job by the way with Zoraxy - big contestender to break the almighty other solutions.
