### ISSUE TITLE
[BUG] Wrong homepage URL in Zoraxy Footer

### ISSUE THREAD

**Issue by MatKlein** [tobychui/zoraxy#326]
**Describe the bug**
There seems to be an incorrect link to the homepage in the footer of the Zoraxy backend. The link https://zoraxy.arozos.com/ leads nowhere. The correct link - at least as of today - would be https://zoraxy.aroz.org/.

**To Reproduce**
1. Go to 'Zoraxy Backend'
2. Click on 'Zoraxy Link in the footer'

**Expected behavior**
Click on the link leads to the correct homepage.

**Comment by PassiveLemon** [comment]
The domain was changed to https://zoraxy.aroz.org/. Details here: https://github.com/tobychui/zoraxy/discussions/325

This will be fixed in the future
