### ISSUE TITLE
[ENHANCEMENTS] ACME Provider for Directadmin

### ISSUE THREAD

**Issue by yllwfsh** [tobychui/zoraxy#327]
**Is your feature request related to a problem? Please describe.**
Trying to get a DNS challenge based certificate from my domains in Directadmin.

**Describe the solution you'd like**
Could you please integrate the https://github.com/go-acme/lego/tree/master/providers/dns/directadmin provider into Zoraxy?

**Comment by Bitti09** [comment]
wait for him to update go-acme from v4.16.1 to at least v4.18.0
cause directadmin was included with v4.18.0: https://github.com/go-acme/lego/releases/tag/v4.18.0

**Comment by yllwfsh** [comment]
I was asking because Directadmin is currently specifically excluded in the build scripts:

https://github.com/tobychui/zoraxy/blob/cf14d12c31bbe1986b33bd2158101b465848c544/tools/dns_challenge_update/code-gen/extract.go#L82


I tried enabling it and built my own docker instance using the build scripts, and can confirm that it is possible to grab a DNS challenge cert via Directadmin:


![image](https://github.com/user-attachments/assets/7f7fbf46-a3ac-4c3d-a806-08003ed0044b)

**Comment by tobychui** [comment]
> I was asking because Directadmin is currently specifically excluded in the build scripts:

It was intentionally disabled due to how Zoraxy is integrating Lego so that no environmental variable is required for ACME related operation. 

When a Zoraxy dependencies update is slower than the lego (repo) update, we will need to comment out those support by lego but not Zoraxy for releaseing. 

I guess we can update the dependencies to support new DNS supplier, but the down side is that we will need to drop Windows 7 support in which I still got a few server in cluster running Windows 7.

**Comment by tobychui** [comment]
Ok, I have added it in but I am not sure will it work or not. Someone will gonna need to test it out after the next release 👍🏻 

![圖片](https://github.com/user-attachments/assets/b1c66fc8-495b-4789-ba80-dff35bca30ee)

**Comment by yllwfsh** [comment]
Thanks very much sir! That looks great, I will check and give you feedback.

**Comment by tobychui** [comment]
Just to remind you that these are in the dev v3.1.2 branch. If you wanna test it, you will need to follow the build from source instructions. But feel free to let me know if it works or not 👍🏻

**Comment by yllwfsh** [comment]
Tried to build the docker container today but couldn't test it fully. I'm getting a 'Internal Server Error' from the web interface. Have no more time today but I can continue the testing the coming days.

Will report back.

**Comment by tobychui** [comment]
@yllwfsh Just a quick tips: You will need to include the web folder in dev branch with the binary. Or you can manually set the following line to use embedded web resources in `main.go` before `go build`

```
development = false     //Set this to false to use embedded web fs
```

**Comment by yllwfsh** [comment]
I see! That makes sense for development. I'll give that parameter a try.

Maybe later today, otherwise tomorrow.

**Comment by yllwfsh** [comment]
@tobychui After changing the development parameter and building the docker container I could successfully get a DNS Challenge cert from Directadmin!

I will continue running this build for now and will report back if I noticed anything, but I think we can consider this one solved for now!

Thanks again for the fast work and your awesome project!
