### ISSUE TITLE
Create an Account

### ISSUE THREAD

**Issue by Kaputtnique** [tobychui/zoraxy#328]
I recreated the Docker Container few times.. 

At the fist Time u have to create an admin account. But if u choose a username and a password and always use "tab" and "Enter" for Confirm.. it runs into an error? i mean, were creating an account and not logging in.

After ich pressed with mouse on "CONFIRM" it worked

**Comment by PassiveLemon** [comment]
I tried highlighting the confirm button with tab but it skips straight from the password field to the link at the bottom of the page, what browser are you using?

**Comment by Kaputtnique** [comment]
firefox 131.0.3

**Comment by PassiveLemon** [comment]
Same here, interesting

**Comment by PassiveLemon** [comment]
Actually, I might have recreated your issue
https://github.com/user-attachments/assets/f3d64f6e-6ff8-42b6-aa5a-c5b8878d7073

**Comment by Kaputtnique** [comment]
exactly. its a bug i would say :-D

**Comment by Kaputtnique** [comment]
![grafik](https://github.com/user-attachments/assets/f74b73fe-afef-4b71-9e41-01e6aa5f5017)
 i added zoraxy on another host. but same problem? i thought its fixed? xD

**Comment by tobychui** [comment]
@Kaputtnique It is fixed in the dev branch, unless you build from source yourself, it will not be available in any release medium (release / docker) at the moment

**Comment by Kaputtnique** [comment]
Alright, sorry :/
