### ISSUE TITLE
[ENHANCEMENTS] Search bar and all Docker Containers

### ISSUE THREAD

**Issue by EasyArt** [tobychui/zoraxy#330]
On the HTTP Proxy Page there should be a search bar ctrl+f filtering the entrys (if you have many entrys its hard to find a specific one)

The Pick from Docker Containers button only shows containers with published ports. I rarely publish ports and zoraxy is member of the same network so zoraxy can connec to the internal ports of the containers it should be possible to select them. (Maybe a checkbox to activate all containers)

**Comment by tobychui** [comment]
Hi @EasyArt 

I feel bad for not replying you with this feature request, but I just wanna to let you know that there are no docker developer for this project (all docker features are contributed by independent users). If you want this feature in Zoraxy, you have to wait for a contributor. Of course, if you wanna give it a try, PRs are always welcomed :)
