### ISSUE TITLE
[ENHANCEMENTS] forward the clients external IP

### ISSUE THREAD

**Issue by bluenazgul** [tobychui/zoraxy#333]
Is there a solutions to get the external Client IP forwared to the proxy Host (Host and Stream Hosts) 

Currently all Hosts only get accessed by the Zoraxy Proxy IP

**Comment by tobychui** [comment]
@bluenazgul Have you tried the advance setting under the custom header snippet tool to see if that fits your needs?
![圖片](https://github.com/user-attachments/assets/f9858407-7d88-46f2-ae92-9ff19640ae39)

Usually the previous node (client) external IP & zoraxy's IP is appended to the `X-Forwarded-For` header following de-facto standard used by other open source reverse proxy / web server projects.  If that is not the case, you can uncheck the `Remove Hop-by-Hop Header` and make Zoraxy kinda `transparent` to the upstream application for testing. If this option is disabled (i.e. Hop-by-hop header is not removed) and your upstream still cannot get the Client IP, then there will be a high chances that you got some networking issues in downstream.

**Comment by tobychui** [comment]
As the `X-Forward-For` and `X-Real-IP` are already there and I guess this request is more like a setup issue of upstream services, I am closing this issue. 
For future visitors, if you want to override the values in default headers, check out the Wiki page for custom headers variables.
