### ISSUE TITLE
[ENHANCEMENTS] IP-Scanner GUI 

### ISSUE THREAD

**Issue by lubeda** [tobychui/zoraxy#342]
If the ip-scanner detects a open http or https service it should make the tick mark to a link to the found service

**Comment by tobychui** [comment]
You know what, I just added it and it feels like easier than I thought.
![464609271_10223102760192248_3647946379906570996_n](https://github.com/user-attachments/assets/82811a98-85f8-4889-a41e-a1063af6fc3e)

You should be able to find it in the next release's Network Tools section next to the IP scanner launcher.
![圖片](https://github.com/user-attachments/assets/5b780ec4-4bb8-4406-bacf-c85fc38bf65c)

**Comment by lubeda** [comment]
Hi, this is huge!

Thanxs
