### ISSUE TITLE
[HELP] Reverseproxy don't work with docker networks

### ISSUE THREAD

**Issue by FuckingToasters** [tobychui/zoraxy#348]
**What happened?**
When making a new proxy rule, the proxy rule don't seem to work at all.

**Describe what have you tried**
I tried to create an proxy rule which points the domain name to the internal hostname of the docker container, which are both `genefit.cc`. The genefit.cc Container, npm Container and zoroxy Container are in the same docker Network, and thus are able to ping each other without the need of externally exposed ports.

I also found out, that the docker socket Integration, only seem to work on containers which have a publicly exposed port:
![grafik](https://github.com/user-attachments/assets/bc7c105c-9323-40d4-95b1-92276a2f4896)

**Describe the networking setup you are using**
- Are you using the docker build of Zoraxy? [yes]
- Your Zoraxy version? [latest]
- Are you using Cloudflare? [yes]
- Are your system hosted under a NAT router? [no]

**Additional context**

**Comment by PassiveLemon** [comment]
This should be fixed in v3.1.4 with the changes to the Docker container list feature. If not, re-open
