### ISSUE TITLE
Access Control - Blacklist - Multiple choice not working

### ISSUE THREAD

**Issue by Kaputtnique** [tobychui/zoraxy#354]
![grafik](https://github.com/user-attachments/assets/cd6eb47e-dda3-4e86-871b-d50d6305d604)

multiple choice of blacklist not working. (firefox)

**Comment by tobychui** [comment]
It works on my machine. 
https://github.com/user-attachments/assets/0b025e1b-fe6c-4c13-be16-30f5c8345e2b

**Comment by Kaputtnique** [comment]
https://github.com/user-attachments/assets/838495ee-dbdd-4e09-b9a3-1f7e244f4a97

**Comment by tobychui** [comment]
@Kaputtnique Thanks for the video, but if there is no way I can reproduce the error and there is no HAR file provided, there isn't much I can do.

**Comment by euklidoid** [comment]
obvisually there is an issue black- and whitelisting. Me, whitelisted EU, but got blocked with German IP and country tag

**Comment by tobychui** [comment]
EU bug in access control has been fixed in v3.1.4
