### ISSUE TITLE
[HELP] Clarify Proxy Header Configuration

### ISSUE THREAD

**Issue by overcuriousity** [tobychui/zoraxy#357]
**Error for Nextcloud while attempting to configure proxy headers**
Operating Nextcloud along other applications in my network.
I am migrating from Nginx Proxy Manager (because of issues with docker). As I am doing okay with general Nginx configuration, I managed to set the headers that no errors show up in the nextcloud configuration in NPM like this:
![image](https://github.com/user-attachments/assets/7d15e85d-3e30-4aeb-8077-1d2c77d2586e)

This configuration does not translate to zoraxy:
![image](https://github.com/user-attachments/assets/afc7e6e5-f43e-4a40-bc42-ebd9280c298a)

results to nextcloud error:
![image](https://github.com/user-attachments/assets/86f824e2-9d46-4c59-8885-704e19949b33)

**Describe what have you tried**
See the configuration above.

**Describe the networking setup you are using**
- Are you using the docker build of Zoraxy? **NO**
- Your Zoraxy version? **3.1.1r3 (latest as of time of issue)**
- Are you using Cloudflare? **NO**
NAT is working.

**Comment by tobychui** [comment]
@overcuriousity I like your question, it is like "why there is no gear stick in my new electric car" 😆. Many people still think Zoraxy is nginx under the hood but it isn't, it is a completely new, build from scratch reverse proxy project.

Back to your question, **Zoraxy does all that automatically.** The custom headers are for manual override to some custom fixed values for legacy projects compatibility that relies on headers for logic processing (Notes: Nowadays, it is a common sense that you should never trust the header sent from the client). Remove all custom headers configs in your Zoraxy and you should be good to go.

**Comment by overcuriousity** [comment]
Thank you for your reply.
Your suggestion didn´t exactly solve the issue, but after doing some research, i discovered i had to set a value in the config.php of nextcloud to:
`'trusted_proxies' => ['192.168.178.103'],`
which was not necessary with the former nginx setup.

But I have to admit, zoraxy is impressive as it is a completely different reverse proxy implementation.

However, I hope it proves to be a secure reverse proxy as it isn´t as widespread and tested as something like nginx. 

I think I will do some pentesting and will share my findings (if any) as this project looks promising.

Keep up the work!
