### ISSUE TITLE
[ENHANCEMENTS] Add Strato as DNS Challenge provider

### ISSUE THREAD

**Issue by Estradamis** [tobychui/zoraxy#361]
**Is your feature request related to a problem? Please describe.**
In the list of DNS Challenge providers, as of now, Strato isn't part of it. Would be good as one of Germany largest (?) webhosters to be in this list

**Describe the solution you'd like**
Having Strato selectable as DNS provider

**Describe alternatives you've considered**
None :)

**Additional context**
Support 2FA with automatic generation of OTP

**Comment by tobychui** [comment]
Hi @Estradamis 

The DNS challenge provider in Zoraxy is provided by the library we used called [lego](https://go-acme.github.io/lego/dns/). 
If you want new DNS provider be supported, please create an issue on their [Github repo](https://github.com/go-acme/lego) and ping me to re-open this issue after they have added it in. Thanks for using Zoraxy :)

**Comment by anubis-genix** [comment]
Apparently there is no API provided by Strato for the DNS challange. 
See https://github.com/go-acme/lego/issues/2197#issuecomment-2137640961
Is there still the possibility to implement the HTML scraping script into Zoraxy?
I'd like to switch over to Zoraxy, but am more or less forced to stick to NPM.

**Comment by anubis-genix** [comment]
I wish I had the skills to do that. The only option that is left, is to switch to a supported domain service provider ;)
Nevertheless, thank you for this great software!
