### ISSUE TITLE
[BUG] Country Whitelisting European Union but blocks German IPs

### ISSUE THREAD

**Issue by euklidoid** [tobychui/zoraxy#378]
**Describe the bug**
Country Whitelisting European Union but blocks German IPs
Error: 404  You do not have permission to view this directory or page.
This might be caused by the region limit setting of this site.

**To Reproduce**
1. Use macOS 15.01 tethered over iOS 18.1
2. Establish LTE connection (o2 Germany)
3. Use Browser [Vivaldi, Brave, Safari] to
4. Access home network to zoraxy to be reproxied to any service (eg. Nextcloud)

**Expected Behaivor**
reproxied to Nextcloud login page

**Work Around**
add Germany to whitelist
(since I dont have a vpn I have no way to check if other EU Countries are effected too. We need to assume that up to 27 countries maybe blocked, even witelisted by selecting EU, So all 27 needs to be varified)

**Screenshots**

![image](https://github.com/user-attachments/assets/6f1d92d2-1102-4c67-a242-afa0906f9c24)

![image](https://github.com/user-attachments/assets/b9265c23-5344-41a4-b38c-137aed9487e5)

**Host Environment (please complete the following information):**
-  Arch: [Intel i5-9600T]
 - Device: [Lenovo Thinkcentre M920x]
 - OS: [Proxmox]
 - Version [8.27 ]
 - VM: [Debian GNU/Linux 12 (bookworm)]
 - Docker Compose (if you are running Zoraxy in docker): [v2.29.7]

**Additional context**
nope

**Comment by euklidoid** [comment]
Please dont remove the EU tag, its so good and makes so much sense  to see that EU as a region is awailble, I did the same exercise with Nextcloud, and there its so awkward to set the countries, with #Command plus left mouse click to mark each line, and if you miss click the whole marked list is gone. 
If there is a easy way to keep a EU tag, that would be awesome.

thanks for coming back so fast

**Comment by euklidoid** [comment]
and by the way, I realized that if you enable GeoBlocking, than I needed to white list my home network, otherwise I got refused. not sure if this is intended.

**Comment by tobychui** [comment]
@euklidoid Well if the EU tag has to be kept, then that means there will be a few more CPU cycles dedicated to resolve the EU country from a list of countries (as the current implementation of gepip uses trie tree, which can only resolve an ip address to a country code in that range). I will see what I can I do. 

>  I realized that if you enable GeoBlocking, than I needed to white list my home network, otherwise I got refused. not sure if this is intended.

GeoIP Access Rules do not have an options for LAN, so yes, you need to add your own home IP range in the whitelist or if you are using a loop-back setup, whitelist your own public IP address.

**Comment by euklidoid** [comment]
about the EU thing, maybe its possible to use the EU tag like a macro, that basically does the manual check of those countries for the user, and then list them indivially or as EU as a whole. I know its a very minor thing, and Im the only one requesting, so whatever you can do is appreciated.

thanks for the great application
