### ISSUE TITLE
[HELP] [Question] Authelia? (OAuth)

### ISSUE THREAD

**Issue by XHyperDEVX** [tobychui/zoraxy#384]
Hello!

I am currently using NPM (NGINX) in my production environment, but I have discovered Zoraxy and I like it so much more!

I would like to switch to Zoraxy, but I have a question: I currently use NPM and [Authelia](https://www.authelia.com/), and would like to keep Authelia.

When I tried Zoraxy in a test environment, I saw that the “SSO/OAuth” tab is still under development.

Are there currently other ways to use Authelia with Zoraxy or would I have to wait until the feature is ready? And if the latter, is there already an NTA for it?

Best regards and thanks for Zoraxy!

**Comment by tobychui** [comment]
Although it is still experimental, but the feature is added. I am closing this now.

**Comment by obkgroove21** [comment]
@tobychui : Do you plan to integrate Keycloak as well?
