### ISSUE TITLE
[BUG] Redirects behind Sub-domain proxy are not working

### ISSUE THREAD

**Issue by Ponkhy** [tobychui/zoraxy#39]
**Describe the bug**
It seems like redirects behind a sub-domain proxy are not working properly. I have two services running behind the reverse proxy [Kutt](https://github.com/thedevs-network/kutt) and [Zipline](https://github.com/diced/zipline), both have url short/redirect functions.
If a user tries to open a shorten url of either service, it does change the path behind the domain, but not the domain it should redirect to, that leads to 404 and other errors.
I haven't found anything to adjust the header or behavior.

**Expected behavior**
The user should be redirected to the appropriate site.

**Host Environment (please complete the following information):**
-  Arch: amd64
 - Device: VM
 - OS: Debian
 - Version 12

**Comment by tobychui** [comment]
Hi @Ponkhy,

I do not personally use Kutt or Zipline, can you provide a few examples of such redirection error and what they are suppose to redirects to? (Like the initial URL, the invalid redirected URL and the URL suppose to be redirected to and any info you think relevant / will help with our debugging)

It would be nice if you could include the browser network tracing dump as well if you know how to generate one. Thanks for raising this issue!

**Comment by Ponkhy** [comment]
Hey @tobychui,

for some weird reason it seems to work now with Zipline, but it still remains with Kutt.

**Shorten URL:** https://url.myon.lu/nuxy
**How it should redirect:** https://cloud.myon.lu/d/26c57ade150f45889f74/?p=%2F&mode=grid
**How it's been redirected with Zoraxy:** https://url.myon.lu/d/26c57ade150f45889f74/?p=%2F&mode=grid

Network Trace (.har): https://cloud.myon.lu/f/f58a79be003f474daf70/

Many thanks!

**Comment by Ponkhy** [comment]
Hey,

I roughly tested the latest commit https://github.com/tobychui/zoraxy/commit/70adadf129c71774ac3f7c66d495934e7763e033 and it indeed seems to fix this problem.
Looking forward to the release, thank you very much!

Many thanks!

**Comment by tobychui** [comment]
Fixed in v2.6.6
