### ISSUE TITLE
[BUG] Version 3.1.3 shows as 3.1.2

### ISSUE THREAD

**Issue by NightHawkATL** [tobychui/zoraxy#393]
**Describe the bug**
I just noticed (through Watchtower) that Zoraxy was just updated after spinning it back up. I had tried to get it to update yesterday but it wouldn't. 

**To Reproduce**
1. update to latest version
2. open Zoraxy Web UI
3. scroll to the bottom

**Expected behavior**
It would be nice to verify that the version was updated correctly.

**Screenshots**
![image](https://github.com/user-attachments/assets/9b0f6638-2152-4c16-bfe2-fc61ef63ef76)
![image](https://github.com/user-attachments/assets/a170a8e6-0a9c-46b3-b518-92ad6974ca81)
![image](https://github.com/user-attachments/assets/930c059c-f25e-40c9-92d3-3930dc4d48c7)

**Browser (if it is a bug appears on the UI section of the system):**

**Host Environment (please complete the following information):**
-  Arch: [e.g. arm64]
 - Device: [e.g. Bananapi R2 PRO]
 - OS: [e.g. Armbian]
 - Version [e.g.  23.02 Bullseye ]
 - Docker Version (if you are running Zoraxy in docker): [e.g. 3.0.4]

**Additional context**

**Comment by tobychui** [comment]
@NightHawkATL  Oh sorry for that, as the CVE fix is a but urgent, plus I have a full time job and only got around 1 - 2 hours each night to get it fixed, I forgot to set the new version in the build pipeline. Will be directly jumping to v3.1.4 in next release.

**Comment by kevinachen12** [comment]
Same Problem :/

**Comment by NightHawkATL** [comment]
> @NightHawkATL Oh sorry for that, as the CVE fix is a but urgent, plus I have a full time job and only got around 1 - 2 hours each night to get it fixed, I forgot to set the new version in the build pipeline. Will be directly jumping to v3.1.4 in next release.
> ## Updates
> 
> I just remember that the UI shd be grabbing the version info from backend instead. From my build I am seeing 3.1.3 on the UI.
> 
> ![圖片](https://private-user-images.githubusercontent.com/24617523/386189794-072ad35a-c6b6-42d1-9f91-af5c979fa1cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MjE3NDksIm5iZiI6MTczMTYyMTQ0OSwicGF0aCI6Ii8yNDYxNzUyMy8zODYxODk3OTQtMDcyYWQzNWEtYzZiNi00MmQxLTlmOTEtYWY1Yzk3OWZhMWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDIxNTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NGE5ZmZlODYxMGUwN2IzNTlkYTkyMjhmYTgwYzEwYzg2Y2ViNzVjNzcwMmQwYTc1YzVkZDEyOThiMDYxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EuvgR6l_10hMxJsC0nFZYeaqLWtggW3KQonhXkGEMDI)
> 
> ![圖片](https://private-user-images.githubusercontent.com/24617523/386189865-cc49ff28-be47-4295-b47c-9d851c595c47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MjE3NDksIm5iZiI6MTczMTYyMTQ0OSwicGF0aCI6Ii8yNDYxNzUyMy8zODYxODk4NjUtY2M0OWZmMjgtYmU0Ny00Mjk1LWI0N2MtOWQ4NTFjNTk1YzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDIxNTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzYTUxNzE3NDJkNGVmY2NkODY5NGIyODA3MTAzOWJmNmZmMjI1OGI1MTdjODY0ZmQ4ZmVjNzhjMzAyOTA1MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q0KNzVmrIumI_BymCXUS77utfQmoSTwTNlaDnvY2TCc)
> 
> You sure that is not a browser cache problem?

![image](https://github.com/user-attachments/assets/2fd9281c-568e-406b-8884-515784fe52b8)

**Comment by tobychui** [comment]
Ok I realized that I have updated the version code in the building pipeline but not the source code, in which if you build from source, the version number will still be v3.1.2. Gonna save up a bit more for a new CICD server later 😶
