### ISSUE TITLE
[ENHANCEMENTS] Additional Headers 

### ISSUE THREAD

**Issue by Saturn745** [tobychui/zoraxy#40]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It would be great to be able to set custom headers on a proxy.

**Describe alternatives you've considered**
Something similar to Nginx Proxy Managers custom config (I know this isn't based on NGINX but would be great to have something to add headers)

**Additional context**
N/A

**Comment by Radiusel** [comment]
Hey TobyChui
Thanks for this nice reverse proxy and the hard work that went into it!
I want to warm up Saturn745's question. I hope I'm in the right place.
I'm also using Zoraxy since a few days (before that Nginx Proxy Manager).
But with Zoraxy I have problems with my web applications,
primarily with Nextcloud. This reports 4 states
Strict-Transport-Security + HSTS + /.well-known/caldav + /.well-known/carddav
which could be changed in the Nginx Proxy Manager by simple settings.
Zoraxy is not a NGINX proxy so my question is, will there be a setting for this for non experienced users?
Please excuse my bad English.
Best regards
Radius
![NC-Sicherheit](https://github.com/tobychui/zoraxy/assets/127239960/3828aa13-cdc9-41f7-b5b9-2d613090b13f)

**Comment by Morethanevil** [comment]
Nextcloud only supports Apache officially. How do you run Nextcloud? Docker or installed on your host?

This would be a valid vHost for Apache. I use it myself and I have Nextcloud on my host without docker. Replace YOUR.DOMAIN.HERE with your domain and check document root.

```
<VirtualHost *:80>
     ServerAdmin admin@example.com
     DocumentRoot /var/www/html/nextcloud/
     ServerName YOUR.DOMAIN.HERE
     <Directory /var/www/html/nextcloud/>
        Options +FollowSymlinks
        AllowOverride All
        Require all granted
          <IfModule mod_dav.c>
            Dav off
          </IfModule>
        SetEnv HOME /var/www/html/nextcloud
        SetEnv HTTP_HOME /var/www/html/nextcloud
  Satisfy Any
</Directory>

<FilesMatch \.php$>
      # For Apache version 2.4.10 and above, use SetHandler to run PHP as a fastCGI process server
      SetHandler "proxy:unix:/run/php/php8.2-fpm.sock|fcgi://localhost"
    </FilesMatch>

<IfModule mod_headers.c>
      Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
    </IfModule>

<IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteCond %{HTTP_USER_AGENT} DavClnt
        RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
        RewriteRule ^remote/(.*) remote.php [QSA,L]
        RewriteRule ^(?:build|tests|config|lib|3rdparty|templates)/.* - [R=404,L]
        RewriteCond %{REQUEST_URI} !^/\.well-known/(acme-challenge|pki-validation)/.*
        RewriteRule ^(?:\.|autotest|occ|issue|indie|db_|console).* - [R=404,L]
</IfModule>

     ErrorLog ${APACHE_LOG_DIR}/error.log
     CustomLog ${APACHE_LOG_DIR}/access.log combined
     LogFormat "%a %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" proxy
</VirtualHost>
```

**Comment by Radiusel** [comment]
Many thanks for the suggestion.
And sorry for the late response.

I have adapted the configs for Nextcloud and a few other websites that I run privately. With my limited technical know-how, it's just my hobby, it takes me (much) longer to convert it.
HTTP/2 support is still missing, but will be implemented soon.
I'm already looking forward to it.

**Comment by tobychui** [comment]
Now with Zoraxy v3, you can add custom headers to a host routing rule as follows.

![圖片](https://github.com/tobychui/zoraxy/assets/24617523/0202abea-3e81-4c17-8f53-98b2f5297b9f)
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/f40f31eb-eea2-4285-8201-317d0b09161c)

**Comment by Nollknolle** [comment]
Is it possible to use vars like $proxy_add_x_forwarded_for for example like in NPM?
