### ISSUE TITLE
[BUG] fatal error: concurrent map writes

### ISSUE THREAD

**Issue by RickoT** [tobychui/zoraxy#401]
**Describe the bug**
After Zoraxy is running for a while, I get this error: fatal error: concurrent map writes with a long stack trace (see attached)

**To Reproduce**
I do not know how to reproduce this, my configuration has been running for months with no issue, then suddenly this started happening within 20 - 30 minutes of starting Zoraxy

**Expected behavior**
No errors and the Proxy continues to run without issues

**Screenshots**
N/A

**Browser (if it is a bug appears on the UI section of the system):**
N/A

**Host Environment (please complete the following information):**
-  Arch: AMD64
- Docker Version Docker version 20.10.24+dfsg1, build 297e128
 - Zoraxy Docker Container Version: 3.1.4

**Additional context**
Log File From Docker: [zoraxy fail log.txt](https://github.com/user-attachments/files/17951586/zoraxy.fail.log.txt)

**Comment by LeonardoIz** [comment]
I think it might be because multiple goroutines are trying to read and write to the s.slowLookupCacheIpv4 map at the same time. In Go, maps are not concurrency-safe, so when this happens without some kind of protection, the program crashes.

**Comment by tobychui** [comment]
@LeonardoIz Thanks for checking the log for me :D 

Yes, it is the issue with the new introduced geoIP database cache mechanism for slow resolve mode. It seems your node have more traffic than my test bench and discovered the implementation defects in the IP resolver. I don't really feel like using mutex for this (as this is blocking and will further slow it down), I will see how can I fix it with maybe syncmap this weekend.

**Comment by RickoT** [comment]
@tobychui 
Thanks for investigating, I have enabled the fastgeoip environment variable in my docker container, I will update if any issues occur.

Thanks!
~Rick

**Comment by rdavey228** [comment]
Im also having this issue and its crashing my container.

I only have 4 proxies setup and I don't get a lot of traffic

I just created a new post before I saw this one. My log file looks the same as RickoT

Here's my post on the issue 

https://github.com/tobychui/zoraxy/issues/437

**Comment by tobychui** [comment]
@rdavey228 This bug has been fixed in the dev branch and will be releasing soon. In the mean time you can enable fast gepIP mode to bypass this bug.
