### ISSUE TITLE
[BUG] Cant disable HSTS on existing Proxy

### ISSUE THREAD

**Issue by Roalkege** [tobychui/zoraxy#415]
**Describe the bug**
I want to disable HSTS on an existing HTTP Proxy

**To Reproduce**
1. Go to HTTP Proxy
2. Select a Proxy with HSTS enabled and click "Edit proxy rules"
3. Click Custom Headers
4. Navigate to security headers.
5. Deactivate the slider
6. Scroll down and click save and after that close
7. Click save
8. Reproduce 2-4 and HSTS is still enabled

**Expected behavior**
HSTS should be disabled for the proxy

**Browser (if it is a bug appears on the UI section of the system):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 131.0.6778.109 

**Host Environment (please complete the following information):**
-  Arch: x64
 - Device: Custom Build
 - OS: Unraid
 - Version 7.0.0-rc.1
 - Docker Version: v.3.1.4

**Comment by tobychui** [comment]
I can reproduce this, but what is weird is that the code that powers this feature never changed since this was introduced. 
Will look into it this weekend.
