### ISSUE TITLE
[BUG] Can't click the checkboxes to renew Certs

### ISSUE THREAD

**Issue by Mike710Shine** [tobychui/zoraxy#422]
**Describe the bug**
My certificate Window is not wide enough to select any cert to renew.

**To Reproduce**
1. Go to 'TLS/SSL certificates'
2. Click on 'Open ACME Tool'
4. See Problem

**Expected behavior**
Maybe change the width from the side window.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/35388026-5316-4272-967c-170ce6106303)

**Browser (if it is a bug appears on the UI section of the system):**
 - Linux CachyOS
 - Browser Chrome and Firefox
 - Version newest

**Host Environment (please complete the following information):**
-  Slackware
 - Server
 - Unraid
 - 7
 - Docker Version 27.0.3

**Additional context**
An alternative would be a Hoirzontale Scrollbar

**Comment by tobychui** [comment]
Fixed, now it can show long hostnames.
![圖片](https://github.com/user-attachments/assets/0818cb35-4c2f-4979-811e-db839249ae99)

**Comment by Mike710Shine** [comment]
Very cool. thanks
