### ISSUE TITLE
[BUG] No credential for dnshome DNS challenge

### ISSUE THREAD

**Issue by GismoNo1** [tobychui/zoraxy#425]
Thanks for the awesome Zoraxy Proxy Manager!

When I try to set up an dns challenge for dnshome.de (supported by lego) there are no fields in the acme-tool to enter my credentials. When trying to issue a certificate this results in an error, because the credentials are missing.

![Bildschirmfoto 2024-12-11 um 13 37 04](https://github.com/user-attachments/assets/36ee3468-273e-425d-8575-793339314ad9)

For the other by lego supported dns provider there are seperate fields for user, password, api_key etc. in the acme-tool Hope you can fix this. Or is there any workaround?

**Comment by tobychui** [comment]
@GismoNo1 

I have checked the automatic generated code for the ACME provider fields and seems the lego implementation is using a string map which the UI code generator cannot parse.

In `mod/acme/acmedns/providers.json`

```json
 "dnshomede": {
  "Name": "dnshomede",
  "ConfigableFields": [
   {
    "Title": "PropagationTimeout",
    "Datatype": "time.Duration"
   },
   {
    "Title": "PollingInterval",
    "Datatype": "time.Duration"
   }
  ],
  "HiddenFields": [
   {
    "Title": "Credentials",
    "Datatype": "map[string]string" //As this is not a key-value set, the UI generator can't generate a web-form for it
   },
   {
    "Title": "HTTPClient",
    "Datatype": "*http.Client"
   }
  ]
 },
```

I guess there isn't anything I can help with this situation. If you would love to get `dnshome.de` supported in Zoraxy, please create a issue / PR on lego repo and ask them to replace this (somewhat poor) implementation to a proper key-value fields like string or int.

**Comment by GismoNo1** [comment]
Well, thank you for your fast reply. I think the lego maintainer also struggeled with the bad dnshome api documentation. [https://github.com/go-acme/lego/issues/1820#issuecomment-1405724506](url)

Maybe right now there is no better solution.
