### ISSUE TITLE
[ENHANCEMENTS] Add option to show error requests

### ISSUE THREAD

**Issue by marchein** [tobychui/zoraxy#429]
Hello, firstly thank you for the great tool!

On the **Statistical Analysis** page there is a counter for total, successful and error requests. 

For me personally it would be a great benefit if I knew which requests led to an error. 

Maybe a possible solution would just to table lists with the hostname, which device requested and a timestamp for both successful and failed requests...

Thanks a lot!

**Comment by zxsa89675** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the DailySummary struct to include RequestDetails, updated the RecordRequest function to store request details, and added a new handler to fetch request details.

You can review changes in this commit: https://github.com/zxsa89675/tobychui-zoraxy-429/commit/1277ad8595468b24d91ce652fcbf03dccf110800.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by tobychui** [comment]
@zxsa89675 I think startups like these should stop using open source projects as free advertisement. These poor AI generated pull requests should not be wasting contributor time to read and test. Latta AI will be added to my blacklist for AI tools.

**Comment by marchein** [comment]
Maybe you did not get my usecase. I use it exclusively in my homelab which is not public facing. 

So there are no bots or something else trying to access my servers...
