### ISSUE TITLE
[BUG] Cannot change inbound port

### ISSUE THREAD

**Issue by rekonnected** [tobychui/zoraxy#43]
**Describe the bug**
When attempting to change the Inbound Port on a fresh installation in Docker, the Apply button does nothing and returns an empty API response console error. The desired value is not saved.

**To Reproduce**
1. Perform a fresh installation of Zoraxy 2.6.5 in Docker.
2. Create the initial user and log in.
3. Change the Inbound Port to any numeric value.
4. Click apply.

**Expected behavior**
The inbound port changes to the specified value.

**Screenshots**
![CleanShot 2023-08-15 at 16 33 46@2x](https://github.com/tobychui/zoraxy/assets/31298266/22a45eb5-a370-403a-944d-fca15d57bad7)

**Browser (if it is a bug appears on the UI section of the system):**
 - OS: macOS 14.0 Sonoma Beta
 - Browser: Brave "Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (arm64)"

**Host Environment (please complete the following information):**
-  Arch: amd64
 - Device: MinisForum UM560X
 - OS: Debian 12 (bookworm)

**Comment by rekonnected** [comment]
Additional error information from docker container log:

```
2023/08/15 20:38:20 http: panic serving <ip redacted>:54939: runtime error: invalid memory address or nil pointer dereference
goroutine 602 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x8a1440?, 0x308cc00?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
main.HandleIncomingPortSet({0x2168618, 0xc0176f21c0}, 0x21636b0?)
	/zoraxy/source/zoraxy/src/reverseproxy.go:652 +0x67
imuslab.com/zoraxy/mod/auth.(*RouterDef).HandleFunc.func1.1({0x2168618?, 0xc0176f21c0?}, 0x500d24?)
	/zoraxy/source/zoraxy/src/mod/auth/router.go:42 +0x22
imuslab.com/zoraxy/mod/auth.(*AuthAgent).HandleCheckAuth(0xc00031c450, {0x2168618, 0xc0176f21c0}, 0xc00002f2d0?, 0xc030e7dab0)
	/zoraxy/source/zoraxy/src/mod/auth/auth.go:84 +0x4c
imuslab.com/zoraxy/mod/auth.(*RouterDef).HandleFunc.func1({0x2168618?, 0xc0176f21c0?}, 0x6af92d?)
	/zoraxy/source/zoraxy/src/mod/auth/router.go:41 +0x58
net/http.HandlerFunc.ServeHTTP(0x10?, {0x2168618?, 0xc0176f21c0?}, 0xc0326966ac?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
net/http.(*ServeMux).ServeHTTP(0x40d385?, {0x2168618, 0xc0176f21c0}, 0xc016a96b00)
	/usr/local/go/src/net/http/server.go:2514 +0x142
net/http.serverHandler.ServeHTTP({0x2166dc0?}, {0x2168618?, 0xc0176f21c0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc03db881b0, {0x21691b0, 0xc03d6b0990})
	/usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 1
	/usr/local/go/src/net/http/server.go:3086 +0x5cb
```

**Comment by tobychui** [comment]
I am not sure about this error, but if you are running zoraxy inside docker, you should not be changing the inbound port inside Zoraxy UI as the inbound port is "proxied" by the docker container. 
I should have handle the error message a bit better, however in this case, if you want to change inbound port in docker environment, I guess what you should change is the docker config (the 80:80 and 433:433 part of the compose file) to other external port you want instead of letting Zoraxy to request a port that is not available.
@PassiveLemon do you have any idea about this?

**Comment by PassiveLemon** [comment]
This is strange, I don't see anything overtly wrong about this approach and I'm fairly certain that I had this running correctly at some point doing essentially the same thing. I'll see if I can recreate it later today.

**Comment by tobychui** [comment]
Ok, I might have figure out what might be the issue here.
@rekonnected have you set your proxy root before starting your reverse proxy?
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/614ff858-4cb1-4c6b-8237-de6519bb4f83)

**Comment by rekonnected** [comment]
I did not, setting that value did finally enable the button to function. I saw the port on the front page and thought to change it first. We should probably have an error box pop up saying something like "Set Proxy Root before changing inbound port" if this is intended behavior. Thank you for finding that so quickly!

**Comment by tobychui** [comment]
A new error message has been added for this bug in v2.6.6. Closing this issue now.
