### ISSUE TITLE
[ENHANCEMENTS] New Default Routing Option: No Response (similar to Nginx 444)

### ISSUE THREAD

**Issue by DerLeole** [tobychui/zoraxy#430]
**Is your feature request related to a problem? Please describe.**
Currently there is no easy way to have zoraxy not respond at all as the default routing option.
One example is that if a subdomain is not present but routed to zoraxy anyways due to a wildcard DNS entry, zoraxy will respond with either a 404 page, a redirect, a forward to an internal target, or the static webserver. However I'd like it to simply not respond at all in cases like this, similar to NPMs "No Response (444)" option.

**Describe the solution you'd like**
Implement a new Default Routing option in which zoraxy simply does not send any response at all and closes the connection.
Inspiration in the implementation can be taken from NPM/Nginx and its 444 response option.

**Describe alternatives you've considered**
The only other way I see that could work right now is to set the default route to a proxy target that does something similar, but I'm not sure if that properly closes the connection or truly sends no data back by default or if it would cause zoraxy to register it as a broken route and display an respond with an error instead.

**Additional context**
The HTTP response code 444 is not an official response code and is only used in NGINX and its paradoxical in itself, as its used whenever there is no response returned, not even the response code itself. So that NGINX terminology can be entirely ignored, I just added it here to make the related functionality easier to find in other projects.

**Comment by tobychui** [comment]
Added
![圖片](https://github.com/user-attachments/assets/c94fdd6b-c8cb-4120-b966-138f6fee06d4)
