### ISSUE TITLE
[HELP] Possible bug

### ISSUE THREAD

**Issue by scoop96** [tobychui/zoraxy#434]
**What happened?**
Lets Encript TLS not working creating the certificate automatically.

 Error: one or more domains had a problem: [proxy.today-song.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 89.29.182.229: Invalid response from http://proxy.xxxxxxxx.com/web/login.html: "\n\n \n \n \n

**Describe what have you tried**
fresh docker compose install in proxmox vm (ubuntu) 
static  IP

Currently i have a Nginx proxy manager working, but im migrating to this.

Also Home assistant is not working in the reverse proxy

**Describe the networking setup you are using**
Here are some example, commonly asked questions from our maintainers: 
- Are you using the docker build of Zoraxy? [yes (with docker setup & networking config attach) /no]
- Your Zoraxy version? latest
- Are you using Cloudflare? yes (no interference in the cloudflare, its only doing CNAME)
- Are your system hosted under a NAT router? [e.g. yes, with subnet is e.g. 192.168.0.0/24 and include port forwarding config if any]
- DNS record (if any)

**Additional context**

**Comment by tobychui** [comment]
Well as you have closed the issue yourself I guess you have already figure out the reasons and fixed it. It would be nice if you could leave your founding here for future visitors :)
