### ISSUE TITLE
[ENHANCEMENTS] Per-Proxy Rule Forced SSL (instead of global)

### ISSUE THREAD

**Issue by rekonnected** [tobychui/zoraxy#44]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to force SSL with simple UI config is globally via the front page. Some of my proxied connections do not require SSL while others do.
![CleanShot 2023-08-16 at 10 49 04@2x](https://github.com/tobychui/zoraxy/assets/31298266/6ce03671-c180-4a57-b155-7ed8c8488e5e)

**Describe the solution you'd like**
I'd like the ability to set, for any individual proxy rule, forced SSL unique to that rule alone. For example, sub.domain.com needs HTTPS, but sub2.domain.com doesn't.

**Describe alternatives you've considered**
NginxProxyManager, a solution many are likely hoping to switch away from (myself included), has fully custom SSL per-rule like so:
![CleanShot 2023-08-16 at 10 46 15@2x](https://github.com/tobychui/zoraxy/assets/31298266/48ade759-1ed7-4a70-a46c-684a60e6e5bb)

Technically, there isn't anything *stopping* me from using wildcards or getting a cert for each domain I want to proxy, but some applications can have issues when HTTPS/SSL is introduced unexpectedly.

**Comment by tobychui** [comment]
Added in v2.6.8
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/e9880b4f-6cea-473f-997c-dbc007a32813)
You can use the "Allow Plain HTTP Access" feature to achieve the same feature you proposed.
