### ISSUE TITLE
[BUG] TLS and Config

### ISSUE THREAD

**Issue by SaschMie** [tobychui/zoraxy#51]
I have some questions that I don't know whether they are bugs or config things:

1.  If I enable TLS on any subdomain, the target is not reachable any more and i get a 404 error. Without the targets are reachable. 

![image](https://github.com/tobychui/zoraxy/assets/101413773/6166720f-75e3-4d4a-8de9-b6330ce79e3a)

2.  Actual Zoraxy is running in Docker, the config "/zoraxy/config/" is connected to local "/mnt/user/appdata/zoraxy", but that path is empty. So i have the feeling if the docker is updating, all the config is gone

**Comment by SaschMie** [comment]
`Actual Zoraxy is running in Docker, the config "/zoraxy/config/" is connected to local "/mnt/user/appdata/zoraxy", but that path is empty. So i have the feeling if the docker is updating, all the config is gone`

This one i found out, in the unraid template there was a blankspace after /mnt/user/appdata/zoraxy, now the config is stored correctly.

**Comment by tobychui** [comment]
@PassiveLemon Can you take a look at this? Thanks!

**Comment by PassiveLemon** [comment]
> This one i found out, in the unraid template there was a blankspace after /mnt/user/appdata/zoraxy, now the config is stored correctly.

That's good to hear

That first part seems like it has to do with Zoraxy itself so @tobychui would be able to offer the best support

**Comment by SaschMie** [comment]
![image](https://github.com/tobychui/zoraxy/assets/101413773/2ed24eed-7dc3-4090-8692-ed9e231e4abf)

Its about TLS, if i activate this on a subdomain, the domain is not working and shows 404. On NPM TLS was working normally.

**Comment by tobychui** [comment]
> ![image](https://user-images.githubusercontent.com/101413773/262594913-2ed24eed-7dc3-4090-8692-ed9e231e4abf.png)
> 
> Its about TLS, if i activate this on a subdomain, the domain is not working and shows 404. On NPM TLS was working normally.

@SaschMie Yes, that is normal. This "Require TLS" is not the same one as the NPM one. The one in Zoraxy means "the proxy target (192.168.50.219 in your case) require HTTPS connection" instead of "Enabling TLS on this subdomain". 

Currently there are no per-subdomain TLS support yet and there are only one global toggle (as shown in the homepage of the management panel). We are working on it now in #44 so please keep an eye on that instead.

**Comment by SaschMie** [comment]
ah okay, then seems this case can be closed.
