### ISSUE TITLE
[ENHANCEMENTS] Letsencrypt Auto Renewal

### ISSUE THREAD

**Issue by Dvalin21** [tobychui/zoraxy#53]
Just as stated.

**Comment by tobychui** [comment]
Have you checkout our ACME auto renew setting panel under TLS / SSL Certificates?

![圖片](https://github.com/tobychui/zoraxy/assets/24617523/3862738a-ef34-4e19-958f-7f28a5e8164e)


You can find the toggle here: 
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/0ac9d69b-4afc-49b6-8702-12cfc338e48f)

**Comment by tobychui** [comment]
Closing because feature already exists
