### ISSUE TITLE
[ENHANCEMENTS] Access list per subdomain

### ISSUE THREAD

**Issue by fa-ve** [tobychui/zoraxy#69]
It would be nice to have an access list per Subdomain next to basic authentication.
This allows only access to specific IP's or Ranges. to subdomains (like NPM Manager)

**Comment by scarulez** [comment]
Agreed. This is really needed

**Comment by Valdun** [comment]
I Agree ! Could be so usefull ! 

I can't move on zorazy without this feature

**Comment by Zettergaard** [comment]
I second this!

**Comment by 7ang0n1n3** [comment]
Is this feature in the pipeline? NGINX Proxy Manager has this function and why it's popular for homelab right now.

**Comment by tobychui** [comment]
@7ang0n1n3 
> Is this feature in the pipeline?

No, there are no contributor picking up this yet. 

> NGINX Proxy Manager has this function and why it's popular for homelab right now.

I am not sure why people love to compare Zoraxy with NPM as I never claim it is a replacement of NPM. But note that this project is only started around 1.5 years ago, you can expect it to lack some features which other older project has.

**Comment by 7ang0n1n3** [comment]
> @7ang0n1n3
> 
> > Is this feature in the pipeline?
> 
> No, there are no contributor picking up this yet.
> 
> > NGINX Proxy Manager has this function and why it's popular for homelab right now.
> 
> I am not sure why people love to compare Zoraxy with NPM as I never claim it is a replacement of NPM. But note that this project is only started around 1.5 years ago, you can expect it to lack some features which other older project has.

I was comparing service and not the coding , don't care if it's NPM/Golang/Rust/C64 Basic. The only function missing that would put Zoraxy ahead the pack , on top, the next big thing. I am generally impressed with the offering and feel the project overall is going in a strong direction.

For such a young project, it has made a pretty good impression I beleive.

**Comment by Mereck13579** [comment]
> I am not sure why people love to compare Zoraxy with NPM (Nginx Proxy Manager) as I never claim it is a replacement of NPM. But note that this project is only started around 1.5 years ago, you can expect it to lack some features which other older project has.

This project is younger than one blocking bug that hasn't been fixed by NPM (which is the reason why I came accross it as I was looking for a replacement) and while it may be lacking some features (such as this one), it overall has more features than NPM...

I wish I could contribute to the code but I'm unfortunately too dumb to code so I'll just chip in and pray that you manage to keep up the good work!

**Comment by tobychui** [comment]
Featured added in v3.0.2
The old access rule will be replaced with the new access control filters. To add access control to an existing HTTP proxy rule, go to Access Control > Access Rule Editor > New
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/9ccbe105-79ea-4f98-800a-11c3b358339c)

Then select the newly created rule from the dropdown list
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/09bc980f-84d8-4f14-95c7-7f70617c6aad)

Edit the access control policy as usual and go to HTTP Proxy, click "edit" on the rule you want to edit and cluck "Access Rule"
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/4fbb7646-7de4-4f3a-b5c4-286e3a336d1c)

Lastly pick your new access rule and apply changes.
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/d5b8b1a4-37fd-4b5c-8059-2e0906875434)

That way, you will have your access rule apply to just the selected HTTP Proxy hostname. For those rules that is not set to any access rule, the "Default" access rules will be used. The Default access rules works like the original "Global" access rule and will apply to all HTTP Proxy hostnames that do not have a set Access Rule ID. 

If anyone is free this weekend, please help move this to Wiki and add some more details. Thank you!

**Comment by Valdun** [comment]
Awesome !! I'll test that and then move from NPM to Zoraxy !!

Thank you !!
