### ISSUE TITLE
[BUG] Very high CPU usage

### ISSUE THREAD

**Issue by AdmiralAwesome** [tobychui/zoraxy#72]
**Describe the bug**
I can see that with the latest update, CPU usage got increased dramatically. And it's at this level almost constantly. Restart of container does not help.

**To Reproduce**
I've installed Zoraxy on proxmox LXC container. In the scree shoot below you can see container configuration.

**Expected behavior**
CPU usage previously was close to being idle.

**Screenshots**
![zoraxy](https://github.com/tobychui/zoraxy/assets/2470577/5f22e285-7124-46eb-be52-90a46baf63a1)

**Host Environment (please complete the following information):**
-  Arch: x64
 - Device: Proxmox LXC
 - OS: Debian
 - Version 12 Bookworm

**Comment by tobychui** [comment]
Hi @AdmiralAwesome,
Might I know the version of Zoraxy you are using and did you enabled the -fastgeoip mode to reduce CPU usage (in exchange for using more RAM)? 
As I got a few private instances of Zoraxy running on my Windows (7) and Linux (debian 11) server without using container. Seems there are no such issues regarding high CPU usage.

**Comment by AdmiralAwesome** [comment]
Well, well, well - could it be that I got barrage of visitors from China/Russia/whatever - as the CPU is fine right now.
![zoraxy2](https://github.com/tobychui/zoraxy/assets/2470577/1954255a-6abb-4074-a4d5-1ab6d7e5cc4f)

It looks like it got a lot of traffic (my timezone is GMT+2)
![image](https://github.com/tobychui/zoraxy/assets/2470577/9867e124-d5c9-4907-8a87-fa4f69f98603)

![image](https://github.com/tobychui/zoraxy/assets/2470577/f036b95b-cacf-4f6e-b8d5-253245aa1888)

I don't have -fastgeoip enabled, but I do have Whitelist enabled just for my Country and the rest of the World is denied.

**Comment by tobychui** [comment]
@AdmiralAwesome 

The whitelist involving the use of country code will force Zoraxy to resolve the request original of each of the incoming request by its IP address, which is a really CPU intensive task if it is done via low memory geoip resolving mode where it needs to iterate through the whole IPv4 (or v6) table before it can respond to the request. 

I am not sure about your hardware specs and visitor counts, but if your server's CPU load is unpleasantly high, I would recommend you to enable fastgeoip mode to save some CPU cycles by space-time-tradeoff country code resolving algorithm.

**Comment by AdmiralAwesome** [comment]
> I am not sure about your hardware specs 
Hardware is not a problem. I can just simply assign more CPU and that's that.

> visitor counts
What is the visitor traffic (based on your experience) to have this kind of load?

**Comment by tobychui** [comment]
> > I am not sure about your hardware specs
> 
> Hardware is not a problem. I can just simply assign more CPU and that's that.
> 
> > visitor counts
> 
> What is the visitor traffic (based on your experience) to have this kind of load?

I never have such high traffic to even utilize 50% of my D525 Intel atom server. Again, without knowing the spec and how many people are visiting your site, I cannot identify if this is a bug from Zoraxy or it is just your machine is too low power to handle the traffics with all the features Zoraxy offer. I guess you need to figure it out yourself.

**Comment by AdmiralAwesome** [comment]
Sure thing. Thank you for your input anyway. It doesn't look like it's Zoraxy bug.
