### ISSUE TITLE
[ENHANCEMENTS] Multiple Subdomains in Single Rule

### ISSUE THREAD

**Issue by evandcombs** [tobychui/zoraxy#76]
**Is your feature request related to a problem? Please describe.**
Only able to include a single subdomain when creating a proxy rule. When having an external and internal domain, users have to create duplicate rules to account for both domains.

**Describe the solution you'd like**
Allow for multiple subdomains to be included when creating a proxy rule. These can be common or semi-colon separated in the Subdomain entry.

**Comment by tobychui** [comment]
Sounds legit, but I don't have much free time to work on Zoraxy recently (it is closing to the end of year and things started to get busy). I will see if I can get it into the next release by Jan 2024 👍🏻

**Comment by tobychui** [comment]
Added in v3.0.2
