### ISSUE TITLE
[QUESTION] Wildcard lets'encrypt certificat 

### ISSUE THREAD

**Issue by barto95100** [tobychui/zoraxy#79]
Just one question how to do that ? lets'encrypt with wildcard ? because if i configure to create one certificat per domain/subdomain i receive the block message acme because mose request .... (I migrate from NPM to zoraxy for test zoraxy solution)

**Comment by tobychui** [comment]
I only know that you can create a cert containing multiple subdomains but I never tried using a wildcard. I guess the ACME module maintainer @yeungalan  might be able to help you with that.

**Comment by barto95100** [comment]
Ok, I used this on NPM with DNS ovh and work good :) 

It's possible to used zoraxy to create a certificat with multiple domaine name ? how to do that ? 

with this section ? 

![CleanShot 2023-11-16 at 15 53 44](https://github.com/tobychui/zoraxy/assets/17863254/f66e7d19-01e6-4f85-9f88-dd355cc0007f)

**Comment by tobychui** [comment]
> Ok, I used this on NPM with DNS ovh and work good :)
> 
> It's possible to used zoraxy to create a certificat with multiple domaine name ? how to do that ?
> 
> with this section ?
> 
> ![CleanShot 2023-11-16 at 15 53 44](https://user-images.githubusercontent.com/17863254/283494175-f66e7d19-01e6-4f85-9f88-dd355cc0007f.png)

Do you mean multiple domains or subdomains? If you want one cert for all your domains, upload them to the Default Certificate section here.
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/c624818b-0ec3-43d0-ba9c-0ed1e28a9d45)

Otherwise, you can use comma separated domains to generate new certificates, like
`s1,example.com,s2.example.com`

**Comment by barto95100** [comment]
Ok i test to add multi domain and its ok for generation certificat:
![CleanShot 2023-11-16 at 16 36 02@2x](https://github.com/tobychui/zoraxy/assets/17863254/feb11587-ef79-489e-8734-27e28f9593c8)


but when I test to add new subdomain on zoraxy, how I can inform zoraxy to use this certificat multi-subdomain ? 

![CleanShot 2023-11-16 at 16 37 42@2x](https://github.com/tobychui/zoraxy/assets/17863254/912ac9d3-bdfd-42f2-9a0f-159414340d1c)

**Comment by Morethanevil** [comment]
Can't you just use *.yourdomain.com for LetsEncrypt? 

I have wildcardcerts for multiple domains from my provider, Zoraxy picks the right one automaticly.

sub.domain1.com uses cert 1, sub.domain2.com uses cert 2. 

No need to set something on this end. The cert only needs to exist

Uncheck "Requieres TLS" and "Skip Verification" from your subdomain proxy. It works without this.

**Comment by barto95100** [comment]
When I test to add *.domain.com "acme-tool" I receive the error:

![CleanShot 2023-11-17 at 11 58 54](https://github.com/tobychui/zoraxy/assets/17863254/52616982-3429-46e4-9e66-fd7397d5b7c0)
and nslookup : 
![CleanShot 2023-11-17 at 11 59 43@2x](https://github.com/tobychui/zoraxy/assets/17863254/98612aee-9972-480e-a9fd-7ce7d762d961)

wildcard is configured on ovh:

*.wxxxxxxxx.fr. | 0 | A | 1xx.xxx.xxx.70
-- | -- | -- | --



Maybe I don't understand how to configure .... :( 

it would actually be simpler to have a wildcard certificate but I can't understand how to do it with zoraxy

**Comment by Morethanevil** [comment]
Try this in OVH:

* 0 A 1xx.xxx.xxx.70

**Comment by barto95100** [comment]
this is already what is configured:
![CleanShot 2023-11-17 at 12 42 06](https://github.com/tobychui/zoraxy/assets/17863254/d658e586-417e-44a3-a0a1-380a5b8560ec)

**Comment by Morethanevil** [comment]
Remove the Dot `.` at the beginning of your domain

**Comment by barto95100** [comment]
it's not possible with gui ovh but in text plain this is the configuration:

![CleanShot 2023-11-17 at 14 04 46@2x](https://github.com/tobychui/zoraxy/assets/17863254/7e04bc44-c27a-4179-af63-18ad2916f382)

**Comment by Morethanevil** [comment]
I had no time yesterday, but today I tested LetsEncrypt with wildcard on my domain. I can confirm your bug in Zoraxy. It is not from OVHs site.

![Screenshot_20231118_092711](https://github.com/tobychui/zoraxy/assets/110860055/f27c0e3c-7107-4b0a-8731-67fea04f38d6)


Please be patient for a bugfix. You can use mutliple SSL providers as a workaround. Some certs from LetsEncrypt for your subdomains, Buypass and ZeroSSL for other subdomains. Buypass and ZeroSSL are european SSL providers, they give free certs too, exactly like LetsEncrypt from america.

**Comment by barto95100** [comment]
Ok no problem I thought I was doing something wrong ;) I test with zerossl :)

**Comment by barto95100** [comment]
any news ?

**Comment by barto95100** [comment]
any news to resolve this problem ? @Morethanevil

**Comment by tobychui** [comment]
@barto95100 
You might try to ping the author of the ACME module @yeungalan or another contributor @daluntw. 
In my opinion, the lego library (which itself support DNS-01 / wildcard certificate challenge) was already used in Zoraxy so I don't think it would be difficult to add support for DNS-01 challenge. I guess the reason that this is still not implemented is mostly due to little incentive from contributors and I am too busy to help.

**Comment by barto95100** [comment]
Excuse if I ping the wrong user... :( my bad 

if the dns-challenge is possible to generate the wildcard is appreciated because, in my case and other (most people test zoraxy now in my entourage) we have multiple sub domain and with limitation of let's encrypt to generate certificate it's a problem because is neccesary to wait 3hours to add new certificate, with wildcard no problem coming soon

**Comment by PastaGringo** [comment]
Hi @barto95100,
I succeed to use a wildcard ssl certificate by generating it with Nginx Proxy Manager and importing it into "Hosts Certificates" section. Seems to work!

**Comment by barto95100** [comment]
> Hi @barto95100, I succeed to use a wildcard ssl certificate by generating it with Nginx Proxy Manager (DNS challenge with OVH) and importing it into "Hosts Certificates" section. Seems to work! PS : you don't have to generate a new ssl certificate each time your create a new Proxy Rule.

YEs I use certbot directly to generate certificate with API OVH and create link symbolic and work perfectly.

I test and i want create a docker image to that

**Comment by nicomda** [comment]
You can integrate LEGO cert with Zoraxy to achieve that https://github.com/go-acme/lego

**Comment by tobychui** [comment]
@nicomda Thanks for the tips. I already mentioned about the use of LEGO in this thread but seems no contributor want to pick it up. I would have add that in by myself if I am not busying with my master thesis. 
If anyone want to integrate this feature and don't know where to starts, please feel free to PM me :)

**Comment by barto95100** [comment]
Just for information i finish the image with zaraxy and Certbot, and work perfectly :) 

The repo :
https://github.com/barto95100/zoraxy

I'm not developper and not possibel for me to help for lego :(

**Comment by haldi4803** [comment]
>I succeed to use a wildcard ssl certificate by generating it with Nginx Proxy Manager (DNS challenge with OVH) and importing it into "Hosts Certificates" section. Seems to work!


Yeah... works for 90 Days.... well good enough for now.

btw, ZeroSSL supports Wildcard Domains only for the 50$/month plan.
`The free Go SSL certificates from Buypass CA doesn’t allow wildcard. It doesn’t mean wildcard isn’t supported at all. Wildcard is a paid product from Buypass CA.`

**Comment by barto95100** [comment]
Yes, it's neccesarry to wait for lets'encrypt added dns challenge on zoraxy +1

**Comment by aweher** [comment]
+1 to have DNS01 support on Zoraxy

Great work guys

**Comment by Teifun2** [comment]
Fyi I think this is covered by the following issue https://github.com/tobychui/zoraxy/issues/49

**Comment by tobychui** [comment]
Featured added in release v3.0.4

**Comment by haldi4803** [comment]
Still get the "could not determine solvers" issue with 3.0.9
Any tips for LetsEncrypt and Wildcards?

**Comment by tobychui** [comment]
> Still get the "could not determine solvers" issue with 3.0.9 Any tips for LetsEncrypt and Wildcards?

Make sure you have no custom DNS like Pihole in your system that blocks some of the required DNS queries and you got the correct API keys for your DNS provider.

**Comment by haldi4803** [comment]
> [Zoraxy](https://zoraxy.arozos.com/) v.3.0.9 © 2021 - 2024 tobychui. Licensed under AGPL
Error: one or more domains had a problem: [*.domain.tld] [*.domain.tld] acme: error presenting token: godaddy: no subdomain because the domain and the zone are identical: domain.tld.
