### ISSUE TITLE
Detached mode and logs

### ISSUE THREAD

**Issue by Morethanevil** [tobychui/zoraxy#8]
First: Thanks for this great program!

I am testing zoraxy inside LXC and I would like to know if there is any detached mode? At the moment I use screen to detach zoraxy output. I can not leave the CLI open the whole time.

It would be cool to start zoraxy with a "-d" argument in the background.

Then I would like to know if there are any logs?

**Comment by Morethanevil** [comment]
Okay now it is running with systemd. Did not think about systemd :D  I needed to modify your scripts and now it runs just fine. For quick testing a "-d" would still be great :)
Please add one of the solutions to the docs.

Here are my steps:

1. Create start.sh in the zoraxy folder with:

```nano start.sh``` 

Put in those lines

``#!/bin/bash
./zoraxy -port=:8000``

2. make executable with

``chmod +x start.sh``

3. Now create systemd-service with 

``sudo nano /etc/systemd/system/zoraxy.service``

Put in following lines:

```
[Unit]
Description=Zoraxy Reverse Proxy Server
After=network-online.target #waits for network to be online
Wants=network-online.target

[Service]
Type=simple

User=root   #no sudo required in start.sh
Group=root
WorkingDirectory=/zoraxy/src/    #folder where zoraxy is
ExecStart=/bin/bash /zoraxy/src/start.sh     #absolute path for start.sh

[Install]
WantedBy=multi-user.target
```


4. Start and enable autostart with:

``sudo systemctl enable --now zoraxy.service``


Now status and logs can be displayed with:

``sudo systemctl status zoraxy``

Logs-files would still be great, but thanks for the help with autostart
A sidenote for LXC-Users: After login as root the working directory is not /zoraxy/src but /root/zoraxy/src
(/root/ is the home of root user) Tested with LXC Ubuntu 22.04

**Comment by TheTaran** [comment]
A litlle fix. :)
[Unit]
Description=Zoraxy Reverse Proxy Server
#waits for network to be online
After=network-online.target
Wants=network-online.target

[Service]
Type=simple

#no sudo required in start.sh
User=root   
Group=root

#folder where zoraxy is
WorkingDirectory=/zoraxy/src/    
#absolute path for start.sh
ExecStart=/bin/bash /zoraxy/src/start.sh     

[Install]
WantedBy=multi-user.target

**Comment by Korenchkin** [comment]
init.d script for those who want (some thin lxc images still use rc.d - alpine for example)
just a basic quick and dirty,restart on crash(should work),no /sys.db but /opt/zoraxy/sys.db ...could be better,but for me directory=/opt/zoraxy as a chdir parameter for supervisor did not work,so hacked a cd and that worked

`#!/sbin/openrc-run

name="zoraxy"
supervisor="supervise-daemon"
#directory="/opt/zoraxy"
command="./zoraxy_linux_amd64"
command_args="-port=:8000"
pidfile="/run/$SVCNAME.pid"

depend() {
        need net
        use dns
}

start_pre()
{
        cd /opt/zoraxy
}
`
