### ISSUE TITLE
[ENHANCEMENTS] "getting started" in documentation

### ISSUE THREAD

**Issue by zammew** [tobychui/zoraxy#86]
hi, I cant seem to figure out the default username and password to login when I first started the app in windows. if you could add a "getting started" page to explain this, it would a lot for me and others.

**Comment by tobychui** [comment]
@zammew are you using a copy from another systems that already have admin account set-up?
If you install it correctly (on windows you just need to double click the exe file, or run as admin if your security setting requires it), you should see the account setup interface when you first start the Zoraxy, as shown in the screenshot below.

![圖片](https://github.com/tobychui/zoraxy/assets/24617523/a5ca0889-10ef-42a3-aae3-615ba328f189)

**Comment by tobychui** [comment]
Getting Started added in Wiki
https://github.com/tobychui/zoraxy/wiki/Getting-Started
