### ISSUE TITLE
Show current version on status page and describe how to update in the docs

### ISSUE THREAD

**Issue by Morethanevil** [tobychui/zoraxy#9]
I just saw news about a new version, but how do I upgrade?

1. Stop zoraxy  service with

`sudo systemctl stop zoraxy`

2. For pulling the sources it is
`git pull`

But I am not familar with go syntax. Do I need to run 
`go mod tidy` and `go build` ? Or is `go build` enough?

After the update zoraxy service can be started again with:

`sudo systemctl start zoraxy`

It would be useful to see which version is used on the status page or in the headline. "Zoraxy v2.6.1" or similar.
Maybe you can build an integrated updater

**Comment by tobychui** [comment]
Yes, the process you describe above is correct. Or you can wait for the release and overwrite the executable (notice some minor issues withe the proxy edit functions, working on it right now).

I think the utilities page will be a better place to put system information, but sure, I will add in a version display into the web ui. For now, you can check it with the following command
```
./zoraxy -version
```
to see which version of zoraxy you are running.
