### ISSUE TITLE
[BUG] Uptime Page probleme "Downstream proxy server is online with misconfigured settings"

### ISSUE THREAD

**Issue by barto95100** [tobychui/zoraxy#91]
The backend is confifured properly... but I don't know why the uptime monitor show this : 
![CleanShot 2024-01-01 at 18 41 48](https://github.com/tobychui/zoraxy/assets/17863254/75c6d07f-a00e-4cd1-9a84-637871100409)

no ssl on backend

**Comment by tobychui** [comment]
The reason the up-time monitor show this is that the target is reachable but gives an HTTP status code of not 200.
I tried your URL and it is not reachable from my side, so you might be using custom DNS or something, which means this is a problem of your network configuration than an actual Zoraxy bug. 

Please tag me to re-open this issue if you have clear evidence that this is a bug generated by Zoraxy.

P.S. reachable in your host doesn't mean the same URL is reachable in your docker container. I am no docker expert so if you need help regarding docker networking, you might need to find PassiveLemon for this matter.

**Comment by tobychui** [comment]
@barto95100 I don't know, I don't use docker. Maybe you can just use your browser to access that endpoint and get me the list of response from your site? (e.g. in browser trace HAR file) Otherwise I have no idea how to help you further.

**Comment by barto95100** [comment]
OK @tobychui 

I install the container with curl commande, configure the container to access the same network of my backend container and test cli command: 

curl -v container_name_backend:port

the result:
```
root@7e59b18dbd73:/# curl -v http://docker-ghostdockercompose-1:2368
*   Trying 172.18.0.4:2368...
* Connected to docker-ghostdockercompose-1 (172.18.0.4) port 2368 (#0)
> GET / HTTP/1.1
> Host: docker-ghostdockercompose-1:2368
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< X-Powered-By: Express
< Cache-Control: public, max-age=31536000
< Location: https://docker-ghostdockercompose-1:2368/
< Vary: Accept, Accept-Encoding
< Content-Type: text/plain; charset=utf-8
< Content-Length: 75
< Date: Wed, 03 Jan 2024 08:30:17 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host docker-ghostdockercompose-1 left intact
Moved Permanently. Redirecting to https://docker-ghostdockercompose-1:2368/
```

**Comment by tobychui** [comment]
@barto95100 cool, this is a helpful bug report you just gave! I will look into this further.

**Comment by tobychui** [comment]
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/17a40255-40a2-4199-a5c6-154976014bf2)

![圖片](https://github.com/tobychui/zoraxy/assets/24617523/2d3b7974-6fdd-4441-a952-f449a7059180)

Cannot reproduce. In fact, the logic in the uptime monitor front-end is as follows.
```javascript
 if (value[value.length - 1].StatusCode >= 500 && value[value.length - 1].StatusCode < 600){
                currentOnlineStatus = `<i class="exclamation circle icon"></i> Misconfigured`;
                onlineStatusCss = `color: #f38020;`;
                reminderEle = `<small style="${onlineStatusCss}">Downstream proxy server is online with misconfigured settings</small>`;
```

This shows that the status code you are getting after the redirection is in the 500 - 600 range. I guess it is really misconfiguration issue instead of a bug in the up time monitor.

**Comment by mflagler** [comment]
I'm also experiencing the same issue with it showing that there's a misconfiguration (although I was just running this as a test to see if it's something I could use). As my test, I just set up "localhost" as my matching domain, and the target IP:PORT which was running on a different PC. The initial page when accessing automatically redirects (302) a few times based on if the user is logged in already or not and to get to a landing page, but the final landing page returns 200. The reverse proxy works fine, but the uptime monitor shows the misconfiguration error mentioned here.

**Comment by tobychui** [comment]
@mflagler Do you have a network trace file for your case? If yes, please open a new issue that specify what system you are using (as downstream) that causes this issue.
