### ISSUE TITLE
[QUESTION] Redirect domaine and not the subdomain

### ISSUE THREAD

**Issue by barto95100** [tobychui/zoraxy#96]
How to configure zoraxy to accept request to https://test.com -> backend ?

I just view to https://forum.test.com -> backend 

and the certificat SSL generated for test.com with lets'encrypt on zoraxy dont work..

How can I do that ?

**Comment by tobychui** [comment]
I am not sure what you mean, but I guess you really need to work on improving your ways to ask a question / raise an issue on Github. 

Maybe can you try to rephrase it a bit or draw some diagram to showcase your issue?

**Comment by barto95100** [comment]
@tobychui my request is simple, how to do so that if ever a user goes to :

https://test.com -> zoraxy -> to 192.168.1.10:8008 

but if ever the user goes to 

https://forum.test. com -> zoraxy -> to 192.168.1.20:80?

currently I have a certificate error and it does not work for certificate "test.com“

**Comment by barto95100** [comment]
> https://forum.test.com is a subdomain and a certificate for https://test.com would not work for the subdomain. You would need either specifically a certificate for the subdomain or a wildcard certificate

YEs I know but, the wildcard with zoraxy don't work with lets'encrypt, zerossl etc...

IT's possible to use certbot or acme.sh to generated a wildcard and send the certificate generated on folder to put the generated certificates in a folder or would zoraxy take them for certificates by default? and also that during renewal it continues to work?

**Comment by tobychui** [comment]
> > https://forum.test.com is a subdomain and a certificate for https://test.com would not work for the subdomain. You would need either specifically a certificate for the subdomain or a wildcard certificate
> 
> YEs I know but, the wildcard with zoraxy don't work with lets'encrypt, zerossl etc...
> 
> IT's possible to use certbot or acme.sh to generated a wildcard and send the certificate generated on folder to put the generated certificates in a folder or would zoraxy take them for certificates by default? and also that during renewal it continues to work?

Yes, you can generate your own cert that contains both domains (forum.test.com and test.com) and throw it into ./conf/certs/ with the filename as "test.com.crt" and "test.com.key". When zoraxy cannot find forum.test.com, it uses the test.com cert instead.

**Comment by barto95100** [comment]
OK another question, It's possible to add on gui Zoraxy the fact that user select the provider (on dropdown menu), and   in gui the news block appear to configure the information  

for exemple ovh need : 
```
dns_ovh_endpoint = ovh-eu
dns_ovh_application_key = 929xxxxx150c
dns_ovh_application_secret = 7xxxxxxxxxxxxxxxxxxxxxxxe
dns_ovh_consumer_key = 90xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx8
```
Zoraxy install the right plugin, certbot use plugins like: 
```
python3-certbot-dns-cloudflare - Cloudflare DNS plugin for Certbot
python3-certbot-dns-digitalocean - DigitalOcean DNS plugin for Certbot
python3-certbot-dns-dnsimple - DNSimple DNS plugin for Certbot
python3-certbot-dns-gandi - Gandi LiveDNS plugin for Certbot
python3-certbot-dns-gehirn - Gehirn DNS plugin for Certbot
python3-certbot-dns-google - Google DNS plugin for Certbot
python3-certbot-dns-linode - Linode DNS plugin for Certbot
python3-certbot-dns-ovh - OVH DNS plugin for Certbot
python3-certbot-dns-rfc2136 - RFC 2136 DNS plugin for Certbot
python3-certbot-dns-route53 - Route53 DNS plugin for Certbot
python3-certbot-dns-sakuracloud - SakuraCloud DNS plugin for Certbot
python3-certbot-dns-standalone - Standalone DNS Authenticator plugin for Certbot
python3-certbot-nginx - Nginx plugin for Certbot
syncplay-server - Synchronize playback of various video players via internet (Server)
```

and zoraxy send command (in background) to generate the certificat : (if ovh is select)

`certbot certonly --dns-ovh --dns-ovh-credentials /root/.ovhapi -d test.com -d *.test.com` -> /root/ovhapi is the file with credential

and save de certificat on the right path (./conf/certs/) or configure file to link
`ln -s /etc/letsencrypt/live/test.com/fullchain.pem ./conf/certs/test.com.crt`
and 
`ln -s /etc/letsencrypt/live/test.com/privkey.pem.pem ./conf/certs/test.com.key`

I don't know if this is possible for you, I am just a simple user of zoraxy dissatisfied with NPM because quite a few problems with it over time and who advertises a lot for zoraxy as it works perfectly well and adds feature that works

I'm not a developer otherwise I would have done my best to help you otherwise :(

**Comment by tobychui** [comment]
Default Site is added to solve the first issue
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/68d873b1-77b0-45d5-821a-f402c119988d)

And if you want to redirect subdomain, use the HTTP Proxy feature (now even support wildcard in both proxy rule and TLS/SSL)
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/ae8a231d-e756-4501-bddf-3567d9ba6c02)

Closing this issue as resolved.
