### ISSUE TITLE
[ENHANCEMENTS] Add comment to IP whitelist entry

### ISSUE THREAD

**Issue by AdmiralAwesome** [tobychui/zoraxy#97]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
![obraz](https://github.com/tobychui/zoraxy/assets/2470577/2a044915-71cd-42d1-8f6a-44f86000aeec)
Just add row for comment to IP whitelist entry, so I'll know which IP is whos to be whitelisted without the need of tracking it in external tool.

**Describe alternatives you've considered**
Notepad. :D

**Additional context**
![obraz](https://github.com/tobychui/zoraxy/assets/2470577/db1fd52b-85db-404f-a4fe-cd393ea0d04a)

Zoraxy is awesome! Thank you!

**Comment by tobychui** [comment]
![圖片](https://github.com/tobychui/zoraxy/assets/24617523/7e843149-e3eb-4cfa-895a-392a3d3ba905)
Added in v3.0.0
