### ISSUE TITLE
sudomain with virtual directories [ENHANCEMENTS]

### ISSUE THREAD

**Issue by jucajuca** [tobychui/zoraxy#99]
**Is your feature request related to a problem? Please describe.**
In many cases you need to groups services together, for example to avoid CORS problems. For example:

service.domain.tld/backend
service.domain.tld/db-manager
service.domain.tld/  --> also a proxy, for example frontend

other-service.domain.tld/sub-service 
other-service.domain.tld/   --> also a proxy, for example frontend

**Describe the solution you'd like**
Function to combine subdomains and virtual folders. In particular virtual folders should be sub-ordinated to sub-domains.
This is offered by apache and nginx. 

**Describe alternatives you've considered**
Using apache or nginx.

**Comment by tobychui** [comment]
Duplicate of #95 
Will pick this up when I got my thesis worked out :)

**Comment by jucajuca** [comment]
closing as it is a duplicate
